// Package push owns SliilS's notification delivery for M11.
//
// Architecture:
//
//   App server ────────────────────────► web push endpoint (Chrome/Firefox/Safari push services)
//   (VAPID signing)                      direct over HTTPS
//
//   App server ────► push-proxy (separate Go service) ────► APNs / FCM / UnifiedPush
//   (install JWT)                                          (proxy speaks the platform APIs)
//
// The proxy exists so the app server never has to ship native Apple/Google
// credentials. The proxy speaks the platforms; we speak to the proxy. For
// web push we don't need a proxy — the browser push service endpoint is
// already public and VAPID signing authenticates us directly.
//
// Payload shape: Signal-style opaque. We send an `msg_id` and `type`. The
// recipient's device hits our tenant server for the actual content. This
// keeps plaintext out of APNs/FCM caches and makes the proxy unable to
// read user messages even if compromised.
package push

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"time"

	webpush "github.com/SherClockHolmes/webpush-go"
)

// Service is the cross-platform delivery facade. Callers (the fan-out
// worker) hand it a Target + Payload; it figures out which driver to use.
type Service struct {
	vapid       vapidKeys
	subject     string // "mailto:admin@sliils.com" — operator contact for push services
	ttlSeconds  int    // how long push services should queue undelivered notifications
	httpClient  *http.Client
	proxy       *ProxyConfig
	logger      *slog.Logger
}

type Options struct {
	// VAPID keys — generated once per install via GenerateVAPIDKeys().
	// Empty means "web push disabled"; the service still accepts
	// registrations but will skip web deliveries.
	VAPIDPublicKey  string
	VAPIDPrivateKey string
	// Subject is the mailto: contact a push service can use to reach the
	// operator if a campaign starts misbehaving. VAPID requires it.
	Subject string
	// TTLSeconds bounds how long the push service queues an undelivered
	// notification. 86400 (24h) is a sensible default.
	TTLSeconds int
	// Proxy is optional — when nil, APNs/FCM/UnifiedPush deliveries are
	// logged + skipped.
	Proxy  *ProxyConfig
	Logger *slog.Logger
}

type ProxyConfig struct {
	// URL of the push-proxy, e.g. https://push.sliils.com.
	URL string
	// InstallJWT is the bearer the proxy will verify. Generated by the
	// proxy operator and handed to the tenant server.
	InstallJWT string
	// TenantID identifies us to the proxy for billing / audit.
	TenantID string
}

type vapidKeys struct {
	pub, priv string
}

// New wires the service. Returns an error only for obviously-broken
// configuration; silent degradation (keys absent → web push skipped)
// lives in the individual drivers.
func New(opts Options) (*Service, error) {
	if opts.Subject == "" {
		opts.Subject = "mailto:push@sliils.local"
	}
	if opts.TTLSeconds <= 0 {
		opts.TTLSeconds = 86400
	}
	if opts.Logger == nil {
		opts.Logger = slog.Default()
	}
	return &Service{
		vapid:      vapidKeys{pub: opts.VAPIDPublicKey, priv: opts.VAPIDPrivateKey},
		subject:    opts.Subject,
		ttlSeconds: opts.TTLSeconds,
		httpClient: &http.Client{Timeout: 10 * time.Second},
		proxy:      opts.Proxy,
		logger:     opts.Logger,
	}, nil
}

// Target describes one device the fan-out wants to reach.
type Target struct {
	DeviceID   int64
	UserID     int64
	Platform   string
	Endpoint   string
	P256DH     string
	AuthSecret string
}

// Payload is the opaque envelope we ship. Keep tiny — APNs caps
// notifications at 4KB; FCM at 4KB data + 2KB notification. Signal-style:
// never include message body here.
type Payload struct {
	MsgID     string `json:"msg_id"`
	Type      string `json:"type"`           // "mention" | "dm" | "call" | "event"
	TenantURL string `json:"tenant_url"`     // which SliilS install issued this (browser uses to know where to fetch)
	TTL       int    `json:"ttl,omitempty"`  // per-push override
}

// Deliver is the single entry point. Returns nil on success,
// ErrGone when the push subscription has expired (caller should
// disable the device), or a generic error otherwise.
func (s *Service) Deliver(ctx context.Context, t Target, p Payload) error {
	switch t.Platform {
	case "web", "tauri":
		return s.deliverWeb(ctx, t, p)
	case "apns", "fcm", "unifiedpush":
		return s.deliverViaProxy(ctx, t, p)
	default:
		return fmt.Errorf("push: unknown platform %q", t.Platform)
	}
}

// ErrGone signals that the recipient's push subscription is permanently
// gone (HTTP 404 or 410). The fan-out worker disables the device.
var ErrGone = errors.New("push: subscription gone")

func (s *Service) deliverWeb(ctx context.Context, t Target, p Payload) error {
	if s.vapid.pub == "" || s.vapid.priv == "" {
		return errors.New("push: VAPID keys not configured; web push disabled")
	}
	body, _ := json.Marshal(p)
	sub := &webpush.Subscription{
		Endpoint: t.Endpoint,
		Keys: webpush.Keys{
			P256dh: t.P256DH,
			Auth:   t.AuthSecret,
		},
	}
	resp, err := webpush.SendNotificationWithContext(ctx, body, sub, &webpush.Options{
		Subscriber:      s.subject,
		VAPIDPublicKey:  s.vapid.pub,
		VAPIDPrivateKey: s.vapid.priv,
		TTL:             s.ttlSeconds,
		HTTPClient:      s.httpClient,
		Urgency:         webpush.UrgencyHigh, // mentions / DMs are not low-priority
	})
	if err != nil {
		return fmt.Errorf("web push send: %w", err)
	}
	defer resp.Body.Close()
	// 201 is the canonical success. 200 + empty body is what Mozilla
	// Push sometimes returns. 4xx lifetime signals require device
	// disabling.
	switch {
	case resp.StatusCode == 404, resp.StatusCode == 410:
		return ErrGone
	case resp.StatusCode >= 200 && resp.StatusCode < 300:
		return nil
	default:
		return fmt.Errorf("web push: unexpected status %d", resp.StatusCode)
	}
}

// deliverViaProxy hands the payload to sliils-push-proxy when configured;
// otherwise logs and skips. The mobile apps' device_tokens still register
// against /me/devices — they just won't receive anything until the proxy
// is deployed.
func (s *Service) deliverViaProxy(ctx context.Context, t Target, p Payload) error {
	if s.proxy == nil || s.proxy.URL == "" {
		s.logger.Debug("push: proxy not configured; skipping",
			slog.Int64("device_id", t.DeviceID),
			slog.String("platform", t.Platform))
		return nil
	}
	body, _ := json.Marshal(map[string]any{
		"tenant_id":    s.proxy.TenantID,
		"device_token": t.Endpoint,
		"platform":     t.Platform,
		"payload":      p,
	})
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, s.proxy.URL+"/v1/notify", io.NopCloser(bytes.NewReader(body)))
	if err != nil {
		return err
	}
	req.Header.Set("Authorization", "Bearer "+s.proxy.InstallJWT)
	req.Header.Set("Content-Type", "application/json")
	resp, err := s.httpClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode == 404 || resp.StatusCode == 410 {
		return ErrGone
	}
	if resp.StatusCode >= 400 {
		return fmt.Errorf("push proxy: status %d", resp.StatusCode)
	}
	return nil
}

// VAPIDPublicKey is what the web client needs to `applicationServerKey`
// its PushManager subscription with. Web pushes only — APNs/FCM don't
// use VAPID.
func (s *Service) VAPIDPublicKey() string { return s.vapid.pub }

// GenerateVAPIDKeys convenience wrapper for first-time setup:
//   priv, pub, _ := push.GenerateVAPIDKeys()
//   // put in env as SLIILS_VAPID_PRIVATE_KEY / SLIILS_VAPID_PUBLIC_KEY
func GenerateVAPIDKeys() (priv, pub string, err error) {
	return webpush.GenerateVAPIDKeys()
}

// DecodeURLSafe is exposed so tests can hand base64url-encoded keys in
// without pulling another dependency.
func DecodeURLSafe(s string) ([]byte, error) {
	return base64.URLEncoding.WithPadding(base64.NoPadding).DecodeString(s)
}

