// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apps.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeOAuthCode = `-- name: ConsumeOAuthCode :one
UPDATE app_oauth_codes
SET used_at = now()
WHERE code = $1
  AND used_at IS NULL
  AND expires_at > now()
RETURNING code, app_id, workspace_id, user_id, redirect_uri, scopes, code_challenge, code_challenge_method, expires_at, used_at, created_at
`

// Single-use exchange: mark used atomically and return the row in one go.
// Returning 0 rows on a used/expired code lets the handler 400 cleanly.
func (q *Queries) ConsumeOAuthCode(ctx context.Context, code string) (AppOauthCode, error) {
	row := q.db.QueryRow(ctx, consumeOAuthCode, code)
	var i AppOauthCode
	err := row.Scan(
		&i.Code,
		&i.AppID,
		&i.WorkspaceID,
		&i.UserID,
		&i.RedirectUri,
		&i.Scopes,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createApp = `-- name: CreateApp :one


INSERT INTO apps (slug, name, description, owner_user_id, avatar_file_id,
                  manifest, client_id, client_secret_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, slug, name, description, owner_user_id, avatar_file_id, manifest, client_id, client_secret_hash, is_public, created_at, deleted_at
`

type CreateAppParams struct {
	Slug             string
	Name             string
	Description      string
	OwnerUserID      int64
	AvatarFileID     *int64
	Manifest         []byte
	ClientID         string
	ClientSecretHash string
}

// Apps platform (M12).
// ---- apps (install-global) ---------------------------------------------
func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) (App, error) {
	row := q.db.QueryRow(ctx, createApp,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.OwnerUserID,
		arg.AvatarFileID,
		arg.Manifest,
		arg.ClientID,
		arg.ClientSecretHash,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.OwnerUserID,
		&i.AvatarFileID,
		&i.Manifest,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.IsPublic,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createAppInstallation = `-- name: CreateAppInstallation :one

INSERT INTO app_installations (app_id, workspace_id, installed_by, scopes, bot_user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, app_id, workspace_id, installed_by, scopes, bot_user_id, created_at, revoked_at
`

type CreateAppInstallationParams struct {
	AppID       int64
	WorkspaceID int64
	InstalledBy *int64
	Scopes      []byte
	BotUserID   *int64
}

// ---- installations -----------------------------------------------------
func (q *Queries) CreateAppInstallation(ctx context.Context, arg CreateAppInstallationParams) (AppInstallation, error) {
	row := q.db.QueryRow(ctx, createAppInstallation,
		arg.AppID,
		arg.WorkspaceID,
		arg.InstalledBy,
		arg.Scopes,
		arg.BotUserID,
	)
	var i AppInstallation
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.WorkspaceID,
		&i.InstalledBy,
		&i.Scopes,
		&i.BotUserID,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createAppToken = `-- name: CreateAppToken :one

INSERT INTO app_tokens (app_installation_id, workspace_id, token_hash, label, scopes)
VALUES ($1, $2, $3, $4, $5)
RETURNING token_id, app_installation_id, workspace_id, token_hash, label, scopes, created_at, last_used_at, revoked_at
`

type CreateAppTokenParams struct {
	AppInstallationID int64
	WorkspaceID       int64
	TokenHash         string
	Label             string
	Scopes            []byte
}

// ---- app tokens --------------------------------------------------------
func (q *Queries) CreateAppToken(ctx context.Context, arg CreateAppTokenParams) (AppToken, error) {
	row := q.db.QueryRow(ctx, createAppToken,
		arg.AppInstallationID,
		arg.WorkspaceID,
		arg.TokenHash,
		arg.Label,
		arg.Scopes,
	)
	var i AppToken
	err := row.Scan(
		&i.TokenID,
		&i.AppInstallationID,
		&i.WorkspaceID,
		&i.TokenHash,
		&i.Label,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createBotUser = `-- name: CreateBotUser :one

INSERT INTO users (email, password_hash, display_name, is_bot, bot_app_installation_id, email_verified_at)
VALUES ($1, NULL, $2, true, $3, now())
RETURNING id, email, password_hash, display_name, avatar_file_id, email_verified_at, totp_secret, locked_until, failed_login_count, created_at, updated_at, deactivated_at, dnd_enabled_until, quiet_hours_start, quiet_hours_end, quiet_hours_tz, is_bot, bot_app_installation_id
`

type CreateBotUserParams struct {
	Email                string
	DisplayName          string
	BotAppInstallationID *int64
}

// ---- bot users ---------------------------------------------------------
// Bot users live in the users table with is_bot=true. Email is a
// synthetic fake@bot.local sentinel so the UNIQUE constraint stays happy.
func (q *Queries) CreateBotUser(ctx context.Context, arg CreateBotUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createBotUser, arg.Email, arg.DisplayName, arg.BotAppInstallationID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarFileID,
		&i.EmailVerifiedAt,
		&i.TotpSecret,
		&i.LockedUntil,
		&i.FailedLoginCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
		&i.DndEnabledUntil,
		&i.QuietHoursStart,
		&i.QuietHoursEnd,
		&i.QuietHoursTz,
		&i.IsBot,
		&i.BotAppInstallationID,
	)
	return i, err
}

const createOAuthCode = `-- name: CreateOAuthCode :exec

INSERT INTO app_oauth_codes
    (code, app_id, workspace_id, user_id, redirect_uri, scopes,
     code_challenge, code_challenge_method, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateOAuthCodeParams struct {
	Code                string
	AppID               int64
	WorkspaceID         int64
	UserID              int64
	RedirectUri         string
	Scopes              []byte
	CodeChallenge       string
	CodeChallengeMethod string
	ExpiresAt           pgtype.Timestamptz
}

// ---- oauth codes -------------------------------------------------------
func (q *Queries) CreateOAuthCode(ctx context.Context, arg CreateOAuthCodeParams) error {
	_, err := q.db.Exec(ctx, createOAuthCode,
		arg.Code,
		arg.AppID,
		arg.WorkspaceID,
		arg.UserID,
		arg.RedirectUri,
		arg.Scopes,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.ExpiresAt,
	)
	return err
}

const getAppByClientID = `-- name: GetAppByClientID :one
SELECT id, slug, name, description, owner_user_id, avatar_file_id, manifest, client_id, client_secret_hash, is_public, created_at, deleted_at FROM apps WHERE client_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAppByClientID(ctx context.Context, clientID string) (App, error) {
	row := q.db.QueryRow(ctx, getAppByClientID, clientID)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.OwnerUserID,
		&i.AvatarFileID,
		&i.Manifest,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.IsPublic,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAppByID = `-- name: GetAppByID :one
SELECT id, slug, name, description, owner_user_id, avatar_file_id, manifest, client_id, client_secret_hash, is_public, created_at, deleted_at FROM apps WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAppByID(ctx context.Context, id int64) (App, error) {
	row := q.db.QueryRow(ctx, getAppByID, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.OwnerUserID,
		&i.AvatarFileID,
		&i.Manifest,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.IsPublic,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAppBySlug = `-- name: GetAppBySlug :one
SELECT id, slug, name, description, owner_user_id, avatar_file_id, manifest, client_id, client_secret_hash, is_public, created_at, deleted_at FROM apps WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAppBySlug(ctx context.Context, slug string) (App, error) {
	row := q.db.QueryRow(ctx, getAppBySlug, slug)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.OwnerUserID,
		&i.AvatarFileID,
		&i.Manifest,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.IsPublic,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAppTokenByID = `-- name: GetAppTokenByID :one
SELECT token_id, app_installation_id, workspace_id, token_hash, label, scopes, created_at, last_used_at, revoked_at FROM app_tokens
WHERE token_id = $1 AND revoked_at IS NULL
`

// Called during inbound bot API requests. Caller verifies the provided
// secret matches the stored hash before trusting the row.
func (q *Queries) GetAppTokenByID(ctx context.Context, tokenID int64) (AppToken, error) {
	row := q.db.QueryRow(ctx, getAppTokenByID, tokenID)
	var i AppToken
	err := row.Scan(
		&i.TokenID,
		&i.AppInstallationID,
		&i.WorkspaceID,
		&i.TokenHash,
		&i.Label,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getBotUserByInstallation = `-- name: GetBotUserByInstallation :one
SELECT id, email, password_hash, display_name, avatar_file_id, email_verified_at, totp_secret, locked_until, failed_login_count, created_at, updated_at, deactivated_at, dnd_enabled_until, quiet_hours_start, quiet_hours_end, quiet_hours_tz, is_bot, bot_app_installation_id FROM users
WHERE bot_app_installation_id = $1 AND is_bot = true AND deactivated_at IS NULL
`

func (q *Queries) GetBotUserByInstallation(ctx context.Context, botAppInstallationID *int64) (User, error) {
	row := q.db.QueryRow(ctx, getBotUserByInstallation, botAppInstallationID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarFileID,
		&i.EmailVerifiedAt,
		&i.TotpSecret,
		&i.LockedUntil,
		&i.FailedLoginCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
		&i.DndEnabledUntil,
		&i.QuietHoursStart,
		&i.QuietHoursEnd,
		&i.QuietHoursTz,
		&i.IsBot,
		&i.BotAppInstallationID,
	)
	return i, err
}

const getInstallation = `-- name: GetInstallation :one
SELECT id, app_id, workspace_id, installed_by, scopes, bot_user_id, created_at, revoked_at FROM app_installations
WHERE app_id = $1 AND workspace_id = $2 AND revoked_at IS NULL
`

type GetInstallationParams struct {
	AppID       int64
	WorkspaceID int64
}

func (q *Queries) GetInstallation(ctx context.Context, arg GetInstallationParams) (AppInstallation, error) {
	row := q.db.QueryRow(ctx, getInstallation, arg.AppID, arg.WorkspaceID)
	var i AppInstallation
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.WorkspaceID,
		&i.InstalledBy,
		&i.Scopes,
		&i.BotUserID,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getInstallationByID = `-- name: GetInstallationByID :one
SELECT id, app_id, workspace_id, installed_by, scopes, bot_user_id, created_at, revoked_at FROM app_installations WHERE id = $1
`

func (q *Queries) GetInstallationByID(ctx context.Context, id int64) (AppInstallation, error) {
	row := q.db.QueryRow(ctx, getInstallationByID, id)
	var i AppInstallation
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.WorkspaceID,
		&i.InstalledBy,
		&i.Scopes,
		&i.BotUserID,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAppsForOwner = `-- name: ListAppsForOwner :many
SELECT id, slug, name, description, owner_user_id, avatar_file_id, manifest, client_id, client_secret_hash, is_public, created_at, deleted_at FROM apps
WHERE  owner_user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAppsForOwner(ctx context.Context, ownerUserID int64) ([]App, error) {
	rows, err := q.db.Query(ctx, listAppsForOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.OwnerUserID,
			&i.AvatarFileID,
			&i.Manifest,
			&i.ClientID,
			&i.ClientSecretHash,
			&i.IsPublic,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstallationsForWorkspace = `-- name: ListInstallationsForWorkspace :many
SELECT ai.id, ai.app_id, ai.workspace_id, ai.installed_by, ai.scopes, ai.bot_user_id, ai.created_at, ai.revoked_at, a.slug, a.name AS app_name, a.description AS app_description
FROM   app_installations ai
JOIN   apps a ON a.id = ai.app_id
WHERE  ai.workspace_id = $1 AND ai.revoked_at IS NULL
ORDER BY ai.created_at DESC
`

type ListInstallationsForWorkspaceRow struct {
	ID             int64
	AppID          int64
	WorkspaceID    int64
	InstalledBy    *int64
	Scopes         []byte
	BotUserID      *int64
	CreatedAt      pgtype.Timestamptz
	RevokedAt      pgtype.Timestamptz
	Slug           string
	AppName        string
	AppDescription string
}

func (q *Queries) ListInstallationsForWorkspace(ctx context.Context, workspaceID int64) ([]ListInstallationsForWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listInstallationsForWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInstallationsForWorkspaceRow{}
	for rows.Next() {
		var i ListInstallationsForWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.WorkspaceID,
			&i.InstalledBy,
			&i.Scopes,
			&i.BotUserID,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.Slug,
			&i.AppName,
			&i.AppDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokensForInstallation = `-- name: ListTokensForInstallation :many
SELECT token_id, app_installation_id, workspace_id, label, scopes,
       created_at, last_used_at, revoked_at
FROM   app_tokens
WHERE  app_installation_id = $1
ORDER BY created_at DESC
`

type ListTokensForInstallationRow struct {
	TokenID           int64
	AppInstallationID int64
	WorkspaceID       int64
	Label             string
	Scopes            []byte
	CreatedAt         pgtype.Timestamptz
	LastUsedAt        pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
}

func (q *Queries) ListTokensForInstallation(ctx context.Context, appInstallationID int64) ([]ListTokensForInstallationRow, error) {
	rows, err := q.db.Query(ctx, listTokensForInstallation, appInstallationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTokensForInstallationRow{}
	for rows.Next() {
		var i ListTokensForInstallationRow
		if err := rows.Scan(
			&i.TokenID,
			&i.AppInstallationID,
			&i.WorkspaceID,
			&i.Label,
			&i.Scopes,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneExpiredOAuthCodes = `-- name: PruneExpiredOAuthCodes :exec
DELETE FROM app_oauth_codes
WHERE expires_at < now() - interval '1 hour'
`

func (q *Queries) PruneExpiredOAuthCodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneExpiredOAuthCodes)
	return err
}

const revokeAppToken = `-- name: RevokeAppToken :exec
UPDATE app_tokens SET revoked_at = now() WHERE token_id = $1
`

func (q *Queries) RevokeAppToken(ctx context.Context, tokenID int64) error {
	_, err := q.db.Exec(ctx, revokeAppToken, tokenID)
	return err
}

const revokeInstallation = `-- name: RevokeInstallation :exec
UPDATE app_installations
SET revoked_at = now()
WHERE id = $1 AND workspace_id = $2
`

type RevokeInstallationParams struct {
	ID          int64
	WorkspaceID int64
}

func (q *Queries) RevokeInstallation(ctx context.Context, arg RevokeInstallationParams) error {
	_, err := q.db.Exec(ctx, revokeInstallation, arg.ID, arg.WorkspaceID)
	return err
}

const rotateAppSecret = `-- name: RotateAppSecret :exec
UPDATE apps
SET client_secret_hash = $2
WHERE id = $1
`

type RotateAppSecretParams struct {
	ID               int64
	ClientSecretHash string
}

func (q *Queries) RotateAppSecret(ctx context.Context, arg RotateAppSecretParams) error {
	_, err := q.db.Exec(ctx, rotateAppSecret, arg.ID, arg.ClientSecretHash)
	return err
}

const setInstallationBot = `-- name: SetInstallationBot :exec
UPDATE app_installations SET bot_user_id = $2 WHERE id = $1
`

type SetInstallationBotParams struct {
	ID        int64
	BotUserID *int64
}

func (q *Queries) SetInstallationBot(ctx context.Context, arg SetInstallationBotParams) error {
	_, err := q.db.Exec(ctx, setInstallationBot, arg.ID, arg.BotUserID)
	return err
}

const softDeleteApp = `-- name: SoftDeleteApp :exec
UPDATE apps SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteApp(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteApp, id)
	return err
}

const touchAppToken = `-- name: TouchAppToken :exec
UPDATE app_tokens SET last_used_at = now() WHERE token_id = $1
`

func (q *Queries) TouchAppToken(ctx context.Context, tokenID int64) error {
	_, err := q.db.Exec(ctx, touchAppToken, tokenID)
	return err
}

const updateAppManifest = `-- name: UpdateAppManifest :one
UPDATE apps
SET manifest    = $1::jsonb,
    name        = COALESCE($2::text, name),
    description = COALESCE($3::text, description)
WHERE id = $4::bigint
RETURNING id, slug, name, description, owner_user_id, avatar_file_id, manifest, client_id, client_secret_hash, is_public, created_at, deleted_at
`

type UpdateAppManifestParams struct {
	Manifest    []byte
	Name        *string
	Description *string
	ID          int64
}

func (q *Queries) UpdateAppManifest(ctx context.Context, arg UpdateAppManifestParams) (App, error) {
	row := q.db.QueryRow(ctx, updateAppManifest,
		arg.Manifest,
		arg.Name,
		arg.Description,
		arg.ID,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.OwnerUserID,
		&i.AvatarFileID,
		&i.Manifest,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.IsPublic,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
