// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlcgen

import (
	"context"
	"net/netip"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (workspace_id, actor_user_id, actor_ip, action, target_kind, target_id, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAuditLogParams struct {
	WorkspaceID *int64
	ActorUserID *int64
	ActorIp     *netip.Addr
	Action      string
	TargetKind  *string
	TargetID    *string
	Metadata    []byte
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.WorkspaceID,
		arg.ActorUserID,
		arg.ActorIp,
		arg.Action,
		arg.TargetKind,
		arg.TargetID,
		arg.Metadata,
	)
	return err
}
