// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_tokens.sql

package sqlcgen

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeAuthToken = `-- name: ConsumeAuthToken :exec
UPDATE auth_tokens
SET consumed_at = now()
WHERE id = $1 AND consumed_at IS NULL
`

func (q *Queries) ConsumeAuthToken(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, consumeAuthToken, id)
	return err
}

const countRecentAuthTokens = `-- name: CountRecentAuthTokens :one
SELECT count(*) AS n
FROM auth_tokens
WHERE user_id = $1
  AND purpose = $2
  AND created_at > now() - ($3 || ' minutes')::interval
`

type CountRecentAuthTokensParams struct {
	UserID  int64
	Purpose string
	Column3 *string
}

func (q *Queries) CountRecentAuthTokens(ctx context.Context, arg CountRecentAuthTokensParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentAuthTokens, arg.UserID, arg.Purpose, arg.Column3)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const createAuthToken = `-- name: CreateAuthToken :one
INSERT INTO auth_tokens (user_id, purpose, token_hash, expires_at, ip)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, purpose, token_hash, created_at, expires_at, consumed_at, ip
`

type CreateAuthTokenParams struct {
	UserID    int64
	Purpose   string
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	Ip        *netip.Addr
}

func (q *Queries) CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) (AuthToken, error) {
	row := q.db.QueryRow(ctx, createAuthToken,
		arg.UserID,
		arg.Purpose,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.Ip,
	)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.Ip,
	)
	return i, err
}

const getAuthTokenByHash = `-- name: GetAuthTokenByHash :one
SELECT id, user_id, purpose, token_hash, created_at, expires_at, consumed_at, ip FROM auth_tokens
WHERE token_hash = $1
  AND purpose    = $2
  AND consumed_at IS NULL
  AND expires_at > now()
`

type GetAuthTokenByHashParams struct {
	TokenHash []byte
	Purpose   string
}

func (q *Queries) GetAuthTokenByHash(ctx context.Context, arg GetAuthTokenByHashParams) (AuthToken, error) {
	row := q.db.QueryRow(ctx, getAuthTokenByHash, arg.TokenHash, arg.Purpose)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.Ip,
	)
	return i, err
}

const invalidateActiveAuthTokens = `-- name: InvalidateActiveAuthTokens :exec
UPDATE auth_tokens
SET consumed_at = now()
WHERE user_id = $1
  AND purpose = $2
  AND consumed_at IS NULL
`

type InvalidateActiveAuthTokensParams struct {
	UserID  int64
	Purpose string
}

func (q *Queries) InvalidateActiveAuthTokens(ctx context.Context, arg InvalidateActiveAuthTokensParams) error {
	_, err := q.db.Exec(ctx, invalidateActiveAuthTokens, arg.UserID, arg.Purpose)
	return err
}
