// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channel_memberships.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMentionsAfter = `-- name: CountMentionsAfter :one
SELECT count(*)::bigint AS n
FROM mentions
WHERE mentioned_user_id = $1
  AND channel_id = $2
  AND message_id > COALESCE($3, 0)
`

type CountMentionsAfterParams struct {
	MentionedUserID int64
	ChannelID       int64
	MessageID       int64
}

func (q *Queries) CountMentionsAfter(ctx context.Context, arg CountMentionsAfterParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMentionsAfter, arg.MentionedUserID, arg.ChannelID, arg.MessageID)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const countMessagesAfter = `-- name: CountMessagesAfter :one
SELECT count(*)::bigint AS n
FROM messages
WHERE channel_id = $1
  AND deleted_at IS NULL
  AND id > COALESCE($2, 0)
  AND created_at >= $3
`

type CountMessagesAfterParams struct {
	ChannelID int64
	ID        int64
	CreatedAt pgtype.Timestamptz
}

// Per-channel unread count. Partitioned messages; the created_at lower
// bound is the message floor we care about.
func (q *Queries) CountMessagesAfter(ctx context.Context, arg CountMessagesAfterParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMessagesAfter, arg.ChannelID, arg.ID, arg.CreatedAt)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const createChannelMembership = `-- name: CreateChannelMembership :one
INSERT INTO channel_memberships (workspace_id, channel_id, user_id, notify_pref)
VALUES ($1, $2, $3, COALESCE($4, 'all'))
ON CONFLICT (channel_id, user_id) DO UPDATE SET notify_pref = EXCLUDED.notify_pref
RETURNING id, workspace_id, channel_id, user_id, notify_pref, last_read_message_id, joined_at, muted_until
`

type CreateChannelMembershipParams struct {
	WorkspaceID int64
	ChannelID   int64
	UserID      int64
	Column4     interface{}
}

func (q *Queries) CreateChannelMembership(ctx context.Context, arg CreateChannelMembershipParams) (ChannelMembership, error) {
	row := q.db.QueryRow(ctx, createChannelMembership,
		arg.WorkspaceID,
		arg.ChannelID,
		arg.UserID,
		arg.Column4,
	)
	var i ChannelMembership
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ChannelID,
		&i.UserID,
		&i.NotifyPref,
		&i.LastReadMessageID,
		&i.JoinedAt,
		&i.MutedUntil,
	)
	return i, err
}

const getChannelMembership = `-- name: GetChannelMembership :one
SELECT id, workspace_id, channel_id, user_id, notify_pref, last_read_message_id, joined_at, muted_until FROM channel_memberships
WHERE channel_id = $1 AND user_id = $2
`

type GetChannelMembershipParams struct {
	ChannelID int64
	UserID    int64
}

func (q *Queries) GetChannelMembership(ctx context.Context, arg GetChannelMembershipParams) (ChannelMembership, error) {
	row := q.db.QueryRow(ctx, getChannelMembership, arg.ChannelID, arg.UserID)
	var i ChannelMembership
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ChannelID,
		&i.UserID,
		&i.NotifyPref,
		&i.LastReadMessageID,
		&i.JoinedAt,
		&i.MutedUntil,
	)
	return i, err
}

const listUserChannelMemberships = `-- name: ListUserChannelMemberships :many
SELECT id, workspace_id, channel_id, user_id, notify_pref, last_read_message_id, joined_at, muted_until FROM channel_memberships
WHERE user_id = $1 AND workspace_id = $2
`

type ListUserChannelMembershipsParams struct {
	UserID      int64
	WorkspaceID int64
}

// Every row for the current user in the current workspace. Drives unread
// badges for the sidebar.
func (q *Queries) ListUserChannelMemberships(ctx context.Context, arg ListUserChannelMembershipsParams) ([]ChannelMembership, error) {
	rows, err := q.db.Query(ctx, listUserChannelMemberships, arg.UserID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelMembership{}
	for rows.Next() {
		var i ChannelMembership
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ChannelID,
			&i.UserID,
			&i.NotifyPref,
			&i.LastReadMessageID,
			&i.JoinedAt,
			&i.MutedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastRead = `-- name: UpdateLastRead :exec
UPDATE channel_memberships
SET last_read_message_id = $3
WHERE channel_id = $1 AND user_id = $2
  AND (last_read_message_id IS NULL OR last_read_message_id < $3)
`

type UpdateLastReadParams struct {
	ChannelID         int64
	UserID            int64
	LastReadMessageID *int64
}

func (q *Queries) UpdateLastRead(ctx context.Context, arg UpdateLastReadParams) error {
	_, err := q.db.Exec(ctx, updateLastRead, arg.ChannelID, arg.UserID, arg.LastReadMessageID)
	return err
}
