// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package sqlcgen

import (
	"context"
)

const archiveChannel = `-- name: ArchiveChannel :exec
UPDATE channels
SET archived_at = now()
WHERE id = $1
`

func (q *Queries) ArchiveChannel(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, archiveChannel, id)
	return err
}

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (workspace_id, type, name, topic, description, default_join, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workspace_id, type, name, topic, description, default_join, created_by, created_at, updated_at, archived_at
`

type CreateChannelParams struct {
	WorkspaceID int64
	Type        string
	Name        *string
	Topic       string
	Description string
	DefaultJoin bool
	CreatedBy   *int64
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.WorkspaceID,
		arg.Type,
		arg.Name,
		arg.Topic,
		arg.Description,
		arg.DefaultJoin,
		arg.CreatedBy,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Type,
		&i.Name,
		&i.Topic,
		&i.Description,
		&i.DefaultJoin,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getChannelByID = `-- name: GetChannelByID :one
SELECT id, workspace_id, type, name, topic, description, default_join, created_by, created_at, updated_at, archived_at FROM channels
WHERE id = $1 AND archived_at IS NULL
`

func (q *Queries) GetChannelByID(ctx context.Context, id int64) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByID, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Type,
		&i.Name,
		&i.Topic,
		&i.Description,
		&i.DefaultJoin,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getChannelByName = `-- name: GetChannelByName :one
SELECT id, workspace_id, type, name, topic, description, default_join, created_by, created_at, updated_at, archived_at FROM channels
WHERE workspace_id = $1 AND name = $2 AND archived_at IS NULL
`

type GetChannelByNameParams struct {
	WorkspaceID int64
	Name        *string
}

func (q *Queries) GetChannelByName(ctx context.Context, arg GetChannelByNameParams) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByName, arg.WorkspaceID, arg.Name)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Type,
		&i.Name,
		&i.Topic,
		&i.Description,
		&i.DefaultJoin,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listPublicChannels = `-- name: ListPublicChannels :many
SELECT id, workspace_id, type, name, topic, description, default_join, created_by, created_at, updated_at, archived_at FROM channels
WHERE type = 'public' AND archived_at IS NULL
ORDER BY name
`

// Lists every non-archived public channel in the current workspace. Private
// channels and DMs show up in M3 once channel_memberships exists.
func (q *Queries) ListPublicChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listPublicChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Type,
			&i.Name,
			&i.Topic,
			&i.Description,
			&i.DefaultJoin,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
