// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteMyDevice = `-- name: DeleteMyDevice :exec
DELETE FROM user_devices
WHERE id = $1 AND user_id = $2
`

type DeleteMyDeviceParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteMyDevice(ctx context.Context, arg DeleteMyDeviceParams) error {
	_, err := q.db.Exec(ctx, deleteMyDevice, arg.ID, arg.UserID)
	return err
}

const disableDevice = `-- name: DisableDevice :exec
UPDATE user_devices
SET disabled_at     = now(),
    disabled_reason = $2
WHERE id = $1
`

type DisableDeviceParams struct {
	ID             int64
	DisabledReason string
}

// Called by the push worker when the endpoint returns 404/410.
func (q *Queries) DisableDevice(ctx context.Context, arg DisableDeviceParams) error {
	_, err := q.db.Exec(ctx, disableDevice, arg.ID, arg.DisabledReason)
	return err
}

const getUserDNDState = `-- name: GetUserDNDState :one
SELECT dnd_enabled_until, quiet_hours_start, quiet_hours_end, quiet_hours_tz
FROM users WHERE id = $1
`

type GetUserDNDStateRow struct {
	DndEnabledUntil pgtype.Timestamptz
	QuietHoursStart *int32
	QuietHoursEnd   *int32
	QuietHoursTz    *string
}

func (q *Queries) GetUserDNDState(ctx context.Context, id int64) (GetUserDNDStateRow, error) {
	row := q.db.QueryRow(ctx, getUserDNDState, id)
	var i GetUserDNDStateRow
	err := row.Scan(
		&i.DndEnabledUntil,
		&i.QuietHoursStart,
		&i.QuietHoursEnd,
		&i.QuietHoursTz,
	)
	return i, err
}

const listDevicesForPush = `-- name: ListDevicesForPush :many
SELECT id, user_id, platform, endpoint, p256dh, auth_secret, user_agent, label, created_at, last_seen_at, disabled_at, disabled_reason FROM user_devices
WHERE  user_id = $1
  AND  disabled_at IS NULL
`

// Hydrates the fan-out worker: every active device for a user.
func (q *Queries) ListDevicesForPush(ctx context.Context, userID int64) ([]UserDevice, error) {
	rows, err := q.db.Query(ctx, listDevicesForPush, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserDevice{}
	for rows.Next() {
		var i UserDevice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.Endpoint,
			&i.P256dh,
			&i.AuthSecret,
			&i.UserAgent,
			&i.Label,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.DisabledAt,
			&i.DisabledReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyDevices = `-- name: ListMyDevices :many
SELECT id, user_id, platform, endpoint, p256dh, auth_secret, user_agent, label, created_at, last_seen_at, disabled_at, disabled_reason FROM user_devices
WHERE  user_id = $1
  AND  disabled_at IS NULL
ORDER BY last_seen_at DESC
`

func (q *Queries) ListMyDevices(ctx context.Context, userID int64) ([]UserDevice, error) {
	rows, err := q.db.Query(ctx, listMyDevices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserDevice{}
	for rows.Next() {
		var i UserDevice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.Endpoint,
			&i.P256dh,
			&i.AuthSecret,
			&i.UserAgent,
			&i.Label,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.DisabledAt,
			&i.DisabledReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerDevice = `-- name: RegisterDevice :one

INSERT INTO user_devices (user_id, platform, endpoint, p256dh, auth_secret, user_agent, label)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id, endpoint) DO UPDATE
SET platform        = EXCLUDED.platform,
    p256dh          = EXCLUDED.p256dh,
    auth_secret     = EXCLUDED.auth_secret,
    user_agent      = EXCLUDED.user_agent,
    label           = EXCLUDED.label,
    disabled_at     = NULL,
    disabled_reason = '',
    last_seen_at    = now()
RETURNING id, user_id, platform, endpoint, p256dh, auth_secret, user_agent, label, created_at, last_seen_at, disabled_at, disabled_reason
`

type RegisterDeviceParams struct {
	UserID     int64
	Platform   string
	Endpoint   string
	P256dh     string
	AuthSecret string
	UserAgent  string
	Label      string
}

// Push notification devices (M11).
// Idempotent by (user_id, endpoint): re-registering the same endpoint
// updates its keys + label and clears disabled state. That matches the
// browser's "I already have a subscription — here it is again" behavior
// where the endpoint stays stable across page reloads.
func (q *Queries) RegisterDevice(ctx context.Context, arg RegisterDeviceParams) (UserDevice, error) {
	row := q.db.QueryRow(ctx, registerDevice,
		arg.UserID,
		arg.Platform,
		arg.Endpoint,
		arg.P256dh,
		arg.AuthSecret,
		arg.UserAgent,
		arg.Label,
	)
	var i UserDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.Endpoint,
		&i.P256dh,
		&i.AuthSecret,
		&i.UserAgent,
		&i.Label,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.DisabledAt,
		&i.DisabledReason,
	)
	return i, err
}

const touchDevice = `-- name: TouchDevice :exec
UPDATE user_devices
SET last_seen_at = now()
WHERE id = $1
`

func (q *Queries) TouchDevice(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchDevice, id)
	return err
}

const updateUserQuietHours = `-- name: UpdateUserQuietHours :exec
UPDATE users
SET dnd_enabled_until = $2,
    quiet_hours_start = $3,
    quiet_hours_end   = $4,
    quiet_hours_tz    = $5,
    updated_at        = now()
WHERE id = $1
`

type UpdateUserQuietHoursParams struct {
	ID              int64
	DndEnabledUntil pgtype.Timestamptz
	QuietHoursStart *int32
	QuietHoursEnd   *int32
	QuietHoursTz    *string
}

func (q *Queries) UpdateUserQuietHours(ctx context.Context, arg UpdateUserQuietHoursParams) error {
	_, err := q.db.Exec(ctx, updateUserQuietHours,
		arg.ID,
		arg.DndEnabledUntil,
		arg.QuietHoursStart,
		arg.QuietHoursEnd,
		arg.QuietHoursTz,
	)
	return err
}
