// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelEvent = `-- name: CancelEvent :exec
UPDATE events
SET canceled_at = now()
WHERE id = $1
`

func (q *Queries) CancelEvent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, cancelEvent, id)
	return err
}

const createEvent = `-- name: CreateEvent :one


INSERT INTO events (
    workspace_id, channel_id, title, description, location_url,
    start_at, end_at, time_zone, rrule,
    recording_enabled, video_enabled, created_by,
    external_provider, external_event_id, external_etag
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, workspace_id, channel_id, title, description, location_url, start_at, end_at, time_zone, rrule, recording_enabled, video_enabled, created_by, created_at, updated_at, canceled_at, external_provider, external_event_id, external_etag
`

type CreateEventParams struct {
	WorkspaceID      int64
	ChannelID        *int64
	Title            string
	Description      string
	LocationUrl      string
	StartAt          pgtype.Timestamptz
	EndAt            pgtype.Timestamptz
	TimeZone         string
	Rrule            *string
	RecordingEnabled bool
	VideoEnabled     bool
	CreatedBy        *int64
	ExternalProvider *string
	ExternalEventID  *string
	ExternalEtag     *string
}

// Calendar events (M9).
// ---- events ------------------------------------------------------------
func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.WorkspaceID,
		arg.ChannelID,
		arg.Title,
		arg.Description,
		arg.LocationUrl,
		arg.StartAt,
		arg.EndAt,
		arg.TimeZone,
		arg.Rrule,
		arg.RecordingEnabled,
		arg.VideoEnabled,
		arg.CreatedBy,
		arg.ExternalProvider,
		arg.ExternalEventID,
		arg.ExternalEtag,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.LocationUrl,
		&i.StartAt,
		&i.EndAt,
		&i.TimeZone,
		&i.Rrule,
		&i.RecordingEnabled,
		&i.VideoEnabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CanceledAt,
		&i.ExternalProvider,
		&i.ExternalEventID,
		&i.ExternalEtag,
	)
	return i, err
}

const getEventByExternalID = `-- name: GetEventByExternalID :one
SELECT id, workspace_id, channel_id, title, description, location_url, start_at, end_at, time_zone, rrule, recording_enabled, video_enabled, created_by, created_at, updated_at, canceled_at, external_provider, external_event_id, external_etag FROM events
WHERE external_provider = $1 AND external_event_id = $2
`

type GetEventByExternalIDParams struct {
	ExternalProvider *string
	ExternalEventID  *string
}

// Dedupe key during pull-from-Google sync. NULL provider/event_id never
// matches (all the fields are enforced non-null by the UNIQUE index).
func (q *Queries) GetEventByExternalID(ctx context.Context, arg GetEventByExternalIDParams) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByExternalID, arg.ExternalProvider, arg.ExternalEventID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.LocationUrl,
		&i.StartAt,
		&i.EndAt,
		&i.TimeZone,
		&i.Rrule,
		&i.RecordingEnabled,
		&i.VideoEnabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CanceledAt,
		&i.ExternalProvider,
		&i.ExternalEventID,
		&i.ExternalEtag,
	)
	return i, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, workspace_id, channel_id, title, description, location_url, start_at, end_at, time_zone, rrule, recording_enabled, video_enabled, created_by, created_at, updated_at, canceled_at, external_provider, external_event_id, external_etag FROM events WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.LocationUrl,
		&i.StartAt,
		&i.EndAt,
		&i.TimeZone,
		&i.Rrule,
		&i.RecordingEnabled,
		&i.VideoEnabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CanceledAt,
		&i.ExternalProvider,
		&i.ExternalEventID,
		&i.ExternalEtag,
	)
	return i, err
}

const listAttendeesForEvent = `-- name: ListAttendeesForEvent :many
SELECT a.id, a.event_id, a.user_id, a.external_email, a.rsvp, a.invited_at, a.responded_at, u.display_name, u.email AS user_email
FROM event_attendees a
LEFT JOIN users u ON u.id = a.user_id
WHERE a.event_id = $1
ORDER BY a.invited_at
`

type ListAttendeesForEventRow struct {
	ID            int64
	EventID       int64
	UserID        *int64
	ExternalEmail *string
	Rsvp          string
	InvitedAt     pgtype.Timestamptz
	RespondedAt   pgtype.Timestamptz
	DisplayName   *string
	UserEmail     *string
}

func (q *Queries) ListAttendeesForEvent(ctx context.Context, eventID int64) ([]ListAttendeesForEventRow, error) {
	rows, err := q.db.Query(ctx, listAttendeesForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttendeesForEventRow{}
	for rows.Next() {
		var i ListAttendeesForEventRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.UserID,
			&i.ExternalEmail,
			&i.Rsvp,
			&i.InvitedAt,
			&i.RespondedAt,
			&i.DisplayName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsForChannel = `-- name: ListEventsForChannel :many
SELECT id, workspace_id, channel_id, title, description, location_url, start_at, end_at, time_zone, rrule, recording_enabled, video_enabled, created_by, created_at, updated_at, canceled_at, external_provider, external_event_id, external_etag FROM events
WHERE channel_id = $1
  AND canceled_at IS NULL
ORDER BY start_at
`

func (q *Queries) ListEventsForChannel(ctx context.Context, channelID *int64) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsForChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ChannelID,
			&i.Title,
			&i.Description,
			&i.LocationUrl,
			&i.StartAt,
			&i.EndAt,
			&i.TimeZone,
			&i.Rrule,
			&i.RecordingEnabled,
			&i.VideoEnabled,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CanceledAt,
			&i.ExternalProvider,
			&i.ExternalEventID,
			&i.ExternalEtag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsInRange = `-- name: ListEventsInRange :many
SELECT e.id, e.workspace_id, e.channel_id, e.title, e.description, e.location_url, e.start_at, e.end_at, e.time_zone, e.rrule, e.recording_enabled, e.video_enabled, e.created_by, e.created_at, e.updated_at, e.canceled_at, e.external_provider, e.external_event_id, e.external_etag, u.display_name AS creator_display_name
FROM events e
LEFT JOIN users u ON u.id = e.created_by
WHERE e.workspace_id = $1
  AND e.canceled_at IS NULL
  AND e.start_at <= $3
  AND (
      -- single instance: end_at inside window
      (e.rrule IS NULL AND e.end_at >= $2)
      -- recurring: included unconditionally; Go-side expander handles
      -- the real range check once RRULE is evaluated.
      OR (e.rrule IS NOT NULL)
  )
ORDER BY e.start_at
`

type ListEventsInRangeParams struct {
	WorkspaceID int64
	EndAt       pgtype.Timestamptz
	StartAt     pgtype.Timestamptz
}

type ListEventsInRangeRow struct {
	ID                 int64
	WorkspaceID        int64
	ChannelID          *int64
	Title              string
	Description        string
	LocationUrl        string
	StartAt            pgtype.Timestamptz
	EndAt              pgtype.Timestamptz
	TimeZone           string
	Rrule              *string
	RecordingEnabled   bool
	VideoEnabled       bool
	CreatedBy          *int64
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	CanceledAt         pgtype.Timestamptz
	ExternalProvider   *string
	ExternalEventID    *string
	ExternalEtag       *string
	CreatorDisplayName *string
}

// Returns every non-canceled event whose "span" could intersect the
// (from, to) window. RRULE expansion happens in Go — this just narrows
// to candidate series by start_at.
//
// Why the generous upper bound on start_at? For a daily recurring event
// whose root is in January, the caller might be asking for a May window.
// Including events whose start_at is <= $3 (the window end) keeps the
// candidate set tight enough while letting the RRULE expander produce
// valid May instances.
func (q *Queries) ListEventsInRange(ctx context.Context, arg ListEventsInRangeParams) ([]ListEventsInRangeRow, error) {
	rows, err := q.db.Query(ctx, listEventsInRange, arg.WorkspaceID, arg.EndAt, arg.StartAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsInRangeRow{}
	for rows.Next() {
		var i ListEventsInRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ChannelID,
			&i.Title,
			&i.Description,
			&i.LocationUrl,
			&i.StartAt,
			&i.EndAt,
			&i.TimeZone,
			&i.Rrule,
			&i.RecordingEnabled,
			&i.VideoEnabled,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CanceledAt,
			&i.ExternalProvider,
			&i.ExternalEventID,
			&i.ExternalEtag,
			&i.CreatorDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingEventsForReminders = `-- name: ListUpcomingEventsForReminders :many
SELECT e.id AS event_id, e.workspace_id, e.channel_id, e.title, e.start_at,
       e.video_enabled, a.user_id
FROM events e
JOIN event_attendees a ON a.event_id = e.id
WHERE e.canceled_at IS NULL
  AND e.start_at BETWEEN (now() + $1::interval)
                     AND (now() + $2::interval)
  AND a.user_id IS NOT NULL
  AND a.rsvp = 'yes'
`

type ListUpcomingEventsForRemindersParams struct {
	LeadMin pgtype.Interval
	LeadMax pgtype.Interval
}

type ListUpcomingEventsForRemindersRow struct {
	EventID      int64
	WorkspaceID  int64
	ChannelID    *int64
	Title        string
	StartAt      pgtype.Timestamptz
	VideoEnabled bool
	UserID       *int64
}

// Drives the River reminder job. Returns events starting in the
// (now + lead_min, now + lead_max) window for users who RSVPd yes.
// The job emits one `event.upcoming` realtime event per (event, user)
// and stamps a reminder_sent sentinel elsewhere (not yet — future).
func (q *Queries) ListUpcomingEventsForReminders(ctx context.Context, arg ListUpcomingEventsForRemindersParams) ([]ListUpcomingEventsForRemindersRow, error) {
	rows, err := q.db.Query(ctx, listUpcomingEventsForReminders, arg.LeadMin, arg.LeadMax)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUpcomingEventsForRemindersRow{}
	for rows.Next() {
		var i ListUpcomingEventsForRemindersRow
		if err := rows.Scan(
			&i.EventID,
			&i.WorkspaceID,
			&i.ChannelID,
			&i.Title,
			&i.StartAt,
			&i.VideoEnabled,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAttendee = `-- name: RemoveAttendee :exec
DELETE FROM event_attendees
WHERE event_id = $1 AND (
    (user_id IS NOT NULL AND user_id = $2)
    OR (external_email IS NOT NULL AND external_email = $3)
)
`

type RemoveAttendeeParams struct {
	EventID       int64
	UserID        *int64
	ExternalEmail *string
}

func (q *Queries) RemoveAttendee(ctx context.Context, arg RemoveAttendeeParams) error {
	_, err := q.db.Exec(ctx, removeAttendee, arg.EventID, arg.UserID, arg.ExternalEmail)
	return err
}

const setEventExternalRef = `-- name: SetEventExternalRef :exec
UPDATE events
SET external_provider = $2,
    external_event_id = $3,
    external_etag     = $4
WHERE id = $1
`

type SetEventExternalRefParams struct {
	ID               int64
	ExternalProvider *string
	ExternalEventID  *string
	ExternalEtag     *string
}

// Stamp the external id + etag after a successful push or on import.
func (q *Queries) SetEventExternalRef(ctx context.Context, arg SetEventExternalRefParams) error {
	_, err := q.db.Exec(ctx, setEventExternalRef,
		arg.ID,
		arg.ExternalProvider,
		arg.ExternalEventID,
		arg.ExternalEtag,
	)
	return err
}

const updateAttendeeRSVP = `-- name: UpdateAttendeeRSVP :one
UPDATE event_attendees
SET rsvp = $3, responded_at = now()
WHERE event_id = $1 AND user_id = $2
RETURNING id, event_id, user_id, external_email, rsvp, invited_at, responded_at
`

type UpdateAttendeeRSVPParams struct {
	EventID int64
	UserID  *int64
	Rsvp    string
}

// Internal users update their own row. The handler enforces ownership;
// the query itself is keyed on (event, user) so crafting a request for
// someone else's row requires writing past the handler's checks.
func (q *Queries) UpdateAttendeeRSVP(ctx context.Context, arg UpdateAttendeeRSVPParams) (EventAttendee, error) {
	row := q.db.QueryRow(ctx, updateAttendeeRSVP, arg.EventID, arg.UserID, arg.Rsvp)
	var i EventAttendee
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.ExternalEmail,
		&i.Rsvp,
		&i.InvitedAt,
		&i.RespondedAt,
	)
	return i, err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET title             = COALESCE($1::text,        title),
    description       = COALESCE($2::text,  description),
    location_url      = COALESCE($3::text, location_url),
    start_at          = COALESCE($4::timestamptz, start_at),
    end_at            = COALESCE($5::timestamptz,   end_at),
    time_zone         = COALESCE($6::text,    time_zone),
    rrule             = $7::text,
    recording_enabled = COALESCE($8::bool, recording_enabled),
    video_enabled     = COALESCE($9::bool,    video_enabled)
WHERE id = $10::bigint
RETURNING id, workspace_id, channel_id, title, description, location_url, start_at, end_at, time_zone, rrule, recording_enabled, video_enabled, created_by, created_at, updated_at, canceled_at, external_provider, external_event_id, external_etag
`

type UpdateEventParams struct {
	Title            *string
	Description      *string
	LocationUrl      *string
	StartAt          pgtype.Timestamptz
	EndAt            pgtype.Timestamptz
	TimeZone         *string
	Rrule            *string
	RecordingEnabled *bool
	VideoEnabled     *bool
	ID               int64
}

// Patch-style update: every field is COALESCE'd so the caller can null-out
// channel_id / rrule / description / location_url etc. by passing an
// explicit value.
func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.Title,
		arg.Description,
		arg.LocationUrl,
		arg.StartAt,
		arg.EndAt,
		arg.TimeZone,
		arg.Rrule,
		arg.RecordingEnabled,
		arg.VideoEnabled,
		arg.ID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.LocationUrl,
		&i.StartAt,
		&i.EndAt,
		&i.TimeZone,
		&i.Rrule,
		&i.RecordingEnabled,
		&i.VideoEnabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CanceledAt,
		&i.ExternalProvider,
		&i.ExternalEventID,
		&i.ExternalEtag,
	)
	return i, err
}

const upsertExternalAttendee = `-- name: UpsertExternalAttendee :one
INSERT INTO event_attendees (event_id, external_email, rsvp)
VALUES ($1, $2, COALESCE($3, 'pending'))
ON CONFLICT (event_id, external_email) WHERE external_email IS NOT NULL
DO UPDATE SET external_email = event_attendees.external_email
RETURNING id, event_id, user_id, external_email, rsvp, invited_at, responded_at
`

type UpsertExternalAttendeeParams struct {
	EventID       int64
	ExternalEmail *string
	Column3       interface{}
}

// Email-only attendees (external guests). Same pattern.
func (q *Queries) UpsertExternalAttendee(ctx context.Context, arg UpsertExternalAttendeeParams) (EventAttendee, error) {
	row := q.db.QueryRow(ctx, upsertExternalAttendee, arg.EventID, arg.ExternalEmail, arg.Column3)
	var i EventAttendee
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.ExternalEmail,
		&i.Rsvp,
		&i.InvitedAt,
		&i.RespondedAt,
	)
	return i, err
}

const upsertInternalAttendee = `-- name: UpsertInternalAttendee :one

INSERT INTO event_attendees (event_id, user_id, rsvp)
VALUES ($1, $2, COALESCE($3, 'pending'))
ON CONFLICT (event_id, user_id) WHERE user_id IS NOT NULL
DO UPDATE SET user_id = event_attendees.user_id  -- no-op
RETURNING id, event_id, user_id, external_email, rsvp, invited_at, responded_at
`

type UpsertInternalAttendeeParams struct {
	EventID int64
	UserID  *int64
	Column3 interface{}
}

// ---- event_attendees ---------------------------------------------------
// Idempotent attendee add for an internal user. If they're already on
// the invite list, we keep their existing RSVP. If this is an import
// from an external calendar, the caller passes rsvp='pending' and the
// next sync tick will reconcile.
func (q *Queries) UpsertInternalAttendee(ctx context.Context, arg UpsertInternalAttendeeParams) (EventAttendee, error) {
	row := q.db.QueryRow(ctx, upsertInternalAttendee, arg.EventID, arg.UserID, arg.Column3)
	var i EventAttendee
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.ExternalEmail,
		&i.Rsvp,
		&i.InvitedAt,
		&i.RespondedAt,
	)
	return i, err
}
