// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: external_calendars.sql

package sqlcgen

import (
	"context"
)

const disconnectExternalCalendar = `-- name: DisconnectExternalCalendar :exec
UPDATE external_calendars
SET disconnected_at = now()
WHERE user_id = $1 AND provider = $2
`

type DisconnectExternalCalendarParams struct {
	UserID   int64
	Provider string
}

func (q *Queries) DisconnectExternalCalendar(ctx context.Context, arg DisconnectExternalCalendarParams) error {
	_, err := q.db.Exec(ctx, disconnectExternalCalendar, arg.UserID, arg.Provider)
	return err
}

const getExternalCalendar = `-- name: GetExternalCalendar :one
SELECT id, user_id, provider, external_account_email, oauth_refresh_token, sync_token, sync_status, last_synced_at, connected_at, disconnected_at FROM external_calendars
WHERE user_id = $1 AND provider = $2 AND disconnected_at IS NULL
`

type GetExternalCalendarParams struct {
	UserID   int64
	Provider string
}

func (q *Queries) GetExternalCalendar(ctx context.Context, arg GetExternalCalendarParams) (ExternalCalendar, error) {
	row := q.db.QueryRow(ctx, getExternalCalendar, arg.UserID, arg.Provider)
	var i ExternalCalendar
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ExternalAccountEmail,
		&i.OauthRefreshToken,
		&i.SyncToken,
		&i.SyncStatus,
		&i.LastSyncedAt,
		&i.ConnectedAt,
		&i.DisconnectedAt,
	)
	return i, err
}

const listActiveExternalCalendars = `-- name: ListActiveExternalCalendars :many
SELECT id, user_id, provider, external_account_email, oauth_refresh_token, sync_token, sync_status, last_synced_at, connected_at, disconnected_at FROM external_calendars WHERE disconnected_at IS NULL
`

// Used by the pull worker. Returns every active connection across every
// user — owner pool only.
func (q *Queries) ListActiveExternalCalendars(ctx context.Context) ([]ExternalCalendar, error) {
	rows, err := q.db.Query(ctx, listActiveExternalCalendars)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExternalCalendar{}
	for rows.Next() {
		var i ExternalCalendar
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ExternalAccountEmail,
			&i.OauthRefreshToken,
			&i.SyncToken,
			&i.SyncStatus,
			&i.LastSyncedAt,
			&i.ConnectedAt,
			&i.DisconnectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExternalCalendarsForUser = `-- name: ListExternalCalendarsForUser :many
SELECT id, user_id, provider, external_account_email, oauth_refresh_token, sync_token, sync_status, last_synced_at, connected_at, disconnected_at FROM external_calendars
WHERE user_id = $1 AND disconnected_at IS NULL
`

func (q *Queries) ListExternalCalendarsForUser(ctx context.Context, userID int64) ([]ExternalCalendar, error) {
	rows, err := q.db.Query(ctx, listExternalCalendarsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExternalCalendar{}
	for rows.Next() {
		var i ExternalCalendar
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ExternalAccountEmail,
			&i.OauthRefreshToken,
			&i.SyncToken,
			&i.SyncStatus,
			&i.LastSyncedAt,
			&i.ConnectedAt,
			&i.DisconnectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExternalCalendarSyncState = `-- name: UpdateExternalCalendarSyncState :exec
UPDATE external_calendars
SET sync_token     = $3,
    last_synced_at = now(),
    sync_status    = COALESCE($4::jsonb, sync_status)
WHERE user_id = $1 AND provider = $2
`

type UpdateExternalCalendarSyncStateParams struct {
	UserID    int64
	Provider  string
	SyncToken *string
	Column4   []byte
}

func (q *Queries) UpdateExternalCalendarSyncState(ctx context.Context, arg UpdateExternalCalendarSyncStateParams) error {
	_, err := q.db.Exec(ctx, updateExternalCalendarSyncState,
		arg.UserID,
		arg.Provider,
		arg.SyncToken,
		arg.Column4,
	)
	return err
}

const upsertExternalCalendar = `-- name: UpsertExternalCalendar :one

INSERT INTO external_calendars (user_id, provider, external_account_email, oauth_refresh_token)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, provider) DO UPDATE
SET external_account_email = EXCLUDED.external_account_email,
    oauth_refresh_token    = EXCLUDED.oauth_refresh_token,
    sync_token             = NULL,
    disconnected_at        = NULL,
    connected_at           = now()
RETURNING id, user_id, provider, external_account_email, oauth_refresh_token, sync_token, sync_status, last_synced_at, connected_at, disconnected_at
`

type UpsertExternalCalendarParams struct {
	UserID               int64
	Provider             string
	ExternalAccountEmail string
	OauthRefreshToken    string
}

// External-calendar connections + sync state (M9-P3).
// Connect or reconnect. When reconnecting after a prior disconnect we
// reset sync_token so the next pull starts from scratch (otherwise a
// stale token tied to a deleted Google connection will 400).
func (q *Queries) UpsertExternalCalendar(ctx context.Context, arg UpsertExternalCalendarParams) (ExternalCalendar, error) {
	row := q.db.QueryRow(ctx, upsertExternalCalendar,
		arg.UserID,
		arg.Provider,
		arg.ExternalAccountEmail,
		arg.OauthRefreshToken,
	)
	var i ExternalCalendar
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ExternalAccountEmail,
		&i.OauthRefreshToken,
		&i.SyncToken,
		&i.SyncStatus,
		&i.LastSyncedAt,
		&i.ConnectedAt,
		&i.DisconnectedAt,
	)
	return i, err
}
