// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO message_attachments (workspace_id, channel_id, message_id, file_id, position)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (message_id, file_id) DO NOTHING
RETURNING id, workspace_id, channel_id, message_id, file_id, position, created_at
`

type CreateAttachmentParams struct {
	WorkspaceID int64
	ChannelID   int64
	MessageID   int64
	FileID      int64
	Position    int32
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (MessageAttachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.WorkspaceID,
		arg.ChannelID,
		arg.MessageID,
		arg.FileID,
		arg.Position,
	)
	var i MessageAttachment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ChannelID,
		&i.MessageID,
		&i.FileID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const createFile = `-- name: CreateFile :one
INSERT INTO files (workspace_id, uploader_user_id, storage_backend, storage_key,
                   filename, mime, size_bytes, sha256, scan_status, width, height)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, workspace_id, uploader_user_id, storage_backend, storage_key, filename, mime, size_bytes, sha256, scan_status, derivatives, width, height, created_at, deleted_at
`

type CreateFileParams struct {
	WorkspaceID    int64
	UploaderUserID *int64
	StorageBackend string
	StorageKey     string
	Filename       string
	Mime           string
	SizeBytes      int64
	Sha256         string
	ScanStatus     string
	Width          *int32
	Height         *int32
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.WorkspaceID,
		arg.UploaderUserID,
		arg.StorageBackend,
		arg.StorageKey,
		arg.Filename,
		arg.Mime,
		arg.SizeBytes,
		arg.Sha256,
		arg.ScanStatus,
		arg.Width,
		arg.Height,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UploaderUserID,
		&i.StorageBackend,
		&i.StorageKey,
		&i.Filename,
		&i.Mime,
		&i.SizeBytes,
		&i.Sha256,
		&i.ScanStatus,
		&i.Derivatives,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, workspace_id, uploader_user_id, storage_backend, storage_key, filename, mime, size_bytes, sha256, scan_status, derivatives, width, height, created_at, deleted_at FROM files
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetFileByID(ctx context.Context, id int64) (File, error) {
	row := q.db.QueryRow(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UploaderUserID,
		&i.StorageBackend,
		&i.StorageKey,
		&i.Filename,
		&i.Mime,
		&i.SizeBytes,
		&i.Sha256,
		&i.ScanStatus,
		&i.Derivatives,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFileBySHA256 = `-- name: GetFileBySHA256 :one
SELECT id, workspace_id, uploader_user_id, storage_backend, storage_key, filename, mime, size_bytes, sha256, scan_status, derivatives, width, height, created_at, deleted_at FROM files
WHERE workspace_id = $1
  AND sha256       = $2
  AND deleted_at IS NULL
`

type GetFileBySHA256Params struct {
	WorkspaceID int64
	Sha256      string
}

// De-dupe lookup: if the same file content is uploaded twice to the same
// workspace, point at the first record instead of creating a duplicate.
func (q *Queries) GetFileBySHA256(ctx context.Context, arg GetFileBySHA256Params) (File, error) {
	row := q.db.QueryRow(ctx, getFileBySHA256, arg.WorkspaceID, arg.Sha256)
	var i File
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UploaderUserID,
		&i.StorageBackend,
		&i.StorageKey,
		&i.Filename,
		&i.Mime,
		&i.SizeBytes,
		&i.Sha256,
		&i.ScanStatus,
		&i.Derivatives,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAttachmentsForMessages = `-- name: ListAttachmentsForMessages :many
SELECT a.message_id, a.position,
       f.id AS file_id, f.filename, f.mime, f.size_bytes,
       f.width, f.height, f.scan_status, f.derivatives, f.created_at
FROM message_attachments a
JOIN files f ON f.id = a.file_id AND f.deleted_at IS NULL
WHERE a.message_id = ANY($1::bigint[])
ORDER BY a.message_id, a.position, a.id
`

type ListAttachmentsForMessagesRow struct {
	MessageID   int64
	Position    int32
	FileID      int64
	Filename    string
	Mime        string
	SizeBytes   int64
	Width       *int32
	Height      *int32
	ScanStatus  string
	Derivatives []byte
	CreatedAt   pgtype.Timestamptz
}

// Hydrates attachments for a batch of messages in a single query. Joined
// against files so the client gets everything it needs to render a preview.
func (q *Queries) ListAttachmentsForMessages(ctx context.Context, dollar_1 []int64) ([]ListAttachmentsForMessagesRow, error) {
	rows, err := q.db.Query(ctx, listAttachmentsForMessages, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttachmentsForMessagesRow{}
	for rows.Next() {
		var i ListAttachmentsForMessagesRow
		if err := rows.Scan(
			&i.MessageID,
			&i.Position,
			&i.FileID,
			&i.Filename,
			&i.Mime,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
			&i.ScanStatus,
			&i.Derivatives,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteFile = `-- name: SoftDeleteFile :exec
UPDATE files
SET deleted_at = now()
WHERE id = $1
`

func (q *Queries) SoftDeleteFile(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteFile, id)
	return err
}

const updateFileBytes = `-- name: UpdateFileBytes :exec
UPDATE files
SET sha256       = $2,
    size_bytes   = $3,
    mime         = $4,
    scan_status  = 'pending'
WHERE id = $1
`

type UpdateFileBytesParams struct {
	ID        int64
	Sha256    string
	SizeBytes int64
	Mime      string
}

// Used by the WOPI PutFile handler when Collabora saves a new version of
// a document. sha256 + size_bytes change; the storage_key stays constant
// so any existing attachments keep pointing at the same file id.
// scan_status resets to 'pending' so the AV worker (M5.1) re-scans once
// it's wired.
func (q *Queries) UpdateFileBytes(ctx context.Context, arg UpdateFileBytesParams) error {
	_, err := q.db.Exec(ctx, updateFileBytes,
		arg.ID,
		arg.Sha256,
		arg.SizeBytes,
		arg.Mime,
	)
	return err
}

const updateFileDerivatives = `-- name: UpdateFileDerivatives :exec
UPDATE files
SET derivatives = $2
WHERE id = $1
`

type UpdateFileDerivativesParams struct {
	ID          int64
	Derivatives []byte
}

func (q *Queries) UpdateFileDerivatives(ctx context.Context, arg UpdateFileDerivativesParams) error {
	_, err := q.db.Exec(ctx, updateFileDerivatives, arg.ID, arg.Derivatives)
	return err
}

const updateFileScanStatus = `-- name: UpdateFileScanStatus :exec
UPDATE files
SET scan_status = $2
WHERE id = $1
`

type UpdateFileScanStatusParams struct {
	ID         int64
	ScanStatus string
}

func (q *Queries) UpdateFileScanStatus(ctx context.Context, arg UpdateFileScanStatusParams) error {
	_, err := q.db.Exec(ctx, updateFileScanStatus, arg.ID, arg.ScanStatus)
	return err
}
