// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: install_settings.sql

package sqlcgen

import (
	"context"
)

const getInstallSetting = `-- name: GetInstallSetting :one

SELECT key, value, encrypted, updated_at, updated_by FROM install_settings WHERE key = $1
`

// Install-wide settings (single-tenant key/value).
func (q *Queries) GetInstallSetting(ctx context.Context, key string) (InstallSetting, error) {
	row := q.db.QueryRow(ctx, getInstallSetting, key)
	var i InstallSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Encrypted,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listInstallSettings = `-- name: ListInstallSettings :many
SELECT key, value, encrypted, updated_at, updated_by FROM install_settings ORDER BY key
`

func (q *Queries) ListInstallSettings(ctx context.Context) ([]InstallSetting, error) {
	rows, err := q.db.Query(ctx, listInstallSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstallSetting{}
	for rows.Next() {
		var i InstallSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Encrypted,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedInstallSettingIfAbsent = `-- name: SeedInstallSettingIfAbsent :exec
INSERT INTO install_settings (key, value, encrypted)
VALUES ($1, $2, $3)
ON CONFLICT (key) DO NOTHING
`

type SeedInstallSettingIfAbsentParams struct {
	Key       string
	Value     string
	Encrypted bool
}

// First-boot seeding: write the value only if the key isn't already
// present. Lets us pull env defaults into the DB once without clobbering
// values an admin has already edited through the UI.
func (q *Queries) SeedInstallSettingIfAbsent(ctx context.Context, arg SeedInstallSettingIfAbsentParams) error {
	_, err := q.db.Exec(ctx, seedInstallSettingIfAbsent, arg.Key, arg.Value, arg.Encrypted)
	return err
}

const upsertInstallSetting = `-- name: UpsertInstallSetting :exec
INSERT INTO install_settings (key, value, encrypted, updated_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (key) DO UPDATE
SET value      = EXCLUDED.value,
    encrypted  = EXCLUDED.encrypted,
    updated_at = now(),
    updated_by = EXCLUDED.updated_by
`

type UpsertInstallSettingParams struct {
	Key       string
	Value     string
	Encrypted bool
	UpdatedBy *int64
}

func (q *Queries) UpsertInstallSetting(ctx context.Context, arg UpsertInstallSettingParams) error {
	_, err := q.db.Exec(ctx, upsertInstallSetting,
		arg.Key,
		arg.Value,
		arg.Encrypted,
		arg.UpdatedBy,
	)
	return err
}
