// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkspaceInvite = `-- name: CreateWorkspaceInvite :one

INSERT INTO workspace_invites (workspace_id, token, email, role, created_by, expires_at)
VALUES ($1, $2, $3, COALESCE($4, 'member'), $5, $6)
RETURNING id, workspace_id, token, email, role, created_by, created_at, expires_at, accepted_at, accepted_by, revoked_at, revoked_by
`

type CreateWorkspaceInviteParams struct {
	WorkspaceID int64
	Token       string
	Email       *string
	Column4     interface{}
	CreatedBy   int64
	ExpiresAt   pgtype.Timestamptz
}

// Workspace invite queries (M7).
//
// Two call paths converge on this table:
//
//	Admin path (runtime pool, sliils_app role): create / list / revoke.
//	  Relies on the invites_modify + invites_select RLS policies in
//	  20260424000002_workspace_invites.sql — the admin must have the GUC
//	  app.workspace_id set to the right workspace.
//
//	Accept path (owner pool, RLS bypassed): lookup by token, mark accepted,
//	  create the workspace_membership. The token is the unguessable handle
//	  so we don't need tenant scope to look it up; we verify the accepting
//	  user's identity at the handler layer.
//
// Called by the admin flow. RLS enforces that app.workspace_id matches
// the row's workspace_id AND the caller is an owner/admin of that
// workspace. Token is generated by the handler and passed in.
func (q *Queries) CreateWorkspaceInvite(ctx context.Context, arg CreateWorkspaceInviteParams) (WorkspaceInvite, error) {
	row := q.db.QueryRow(ctx, createWorkspaceInvite,
		arg.WorkspaceID,
		arg.Token,
		arg.Email,
		arg.Column4,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i WorkspaceInvite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Token,
		&i.Email,
		&i.Role,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}

const getInviteByToken = `-- name: GetInviteByToken :one
SELECT i.id, i.workspace_id, i.token, i.email, i.role,
       i.created_by, i.created_at, i.expires_at,
       i.accepted_at, i.accepted_by, i.revoked_at,
       w.slug AS workspace_slug, w.name AS workspace_name,
       w.description AS workspace_description
FROM workspace_invites i
JOIN workspaces w ON w.id = i.workspace_id
WHERE i.token = $1
`

type GetInviteByTokenRow struct {
	ID                   int64
	WorkspaceID          int64
	Token                string
	Email                *string
	Role                 string
	CreatedBy            int64
	CreatedAt            pgtype.Timestamptz
	ExpiresAt            pgtype.Timestamptz
	AcceptedAt           pgtype.Timestamptz
	AcceptedBy           *int64
	RevokedAt            pgtype.Timestamptz
	WorkspaceSlug        string
	WorkspaceName        string
	WorkspaceDescription string
}

// Token lookup. Runs on the OWNER pool (RLS bypassed) so the accept path
// can find the invite without knowing the workspace id. The handler
// validates expiry + revoked + accepted + email-match server-side before
// acting on the result.
func (q *Queries) GetInviteByToken(ctx context.Context, token string) (GetInviteByTokenRow, error) {
	row := q.db.QueryRow(ctx, getInviteByToken, token)
	var i GetInviteByTokenRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Token,
		&i.Email,
		&i.Role,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.WorkspaceSlug,
		&i.WorkspaceName,
		&i.WorkspaceDescription,
	)
	return i, err
}

const insertWorkspaceMembershipFromInvite = `-- name: InsertWorkspaceMembershipFromInvite :one
INSERT INTO workspace_memberships (workspace_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (workspace_id, user_id)
DO UPDATE SET
    deactivated_at = NULL,
    role = EXCLUDED.role
RETURNING id, workspace_id, user_id, role, custom_status, joined_at, deactivated_at, notify_pref
`

type InsertWorkspaceMembershipFromInviteParams struct {
	WorkspaceID int64
	UserID      int64
	Role        string
}

// Owner-pool path for the accept. Bypasses the workspace_memberships
// RLS policy (which requires app.workspace_id to be set — we don't
// set it here because the accepting user hasn't "selected" the workspace
// in their session yet). Safe because the token lookup above already
// proved the caller's right to enroll.
func (q *Queries) InsertWorkspaceMembershipFromInvite(ctx context.Context, arg InsertWorkspaceMembershipFromInviteParams) (WorkspaceMembership, error) {
	row := q.db.QueryRow(ctx, insertWorkspaceMembershipFromInvite, arg.WorkspaceID, arg.UserID, arg.Role)
	var i WorkspaceMembership
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CustomStatus,
		&i.JoinedAt,
		&i.DeactivatedAt,
		&i.NotifyPref,
	)
	return i, err
}

const listPendingInvitesForWorkspace = `-- name: ListPendingInvitesForWorkspace :many
SELECT i.id, i.workspace_id, i.token, i.email, i.role,
       i.created_by, i.created_at, i.expires_at,
       u.display_name AS creator_display_name, u.email AS creator_email
FROM workspace_invites i
LEFT JOIN users u ON u.id = i.created_by
WHERE i.workspace_id = $1
  AND i.accepted_at IS NULL
  AND i.revoked_at IS NULL
ORDER BY i.created_at DESC
`

type ListPendingInvitesForWorkspaceRow struct {
	ID                 int64
	WorkspaceID        int64
	Token              string
	Email              *string
	Role               string
	CreatedBy          int64
	CreatedAt          pgtype.Timestamptz
	ExpiresAt          pgtype.Timestamptz
	CreatorDisplayName *string
	CreatorEmail       *string
}

// Admin-facing list of outstanding invites. The partial index drives this.
func (q *Queries) ListPendingInvitesForWorkspace(ctx context.Context, workspaceID int64) ([]ListPendingInvitesForWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listPendingInvitesForWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingInvitesForWorkspaceRow{}
	for rows.Next() {
		var i ListPendingInvitesForWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Token,
			&i.Email,
			&i.Role,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.CreatorDisplayName,
			&i.CreatorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInviteAccepted = `-- name: MarkInviteAccepted :exec
UPDATE workspace_invites
SET accepted_at = now(), accepted_by = $2
WHERE id = $1
  AND accepted_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > now()
`

type MarkInviteAcceptedParams struct {
	ID         int64
	AcceptedBy *int64
}

// Owner-pool path. Stamps the accept so the same token can't be reused.
func (q *Queries) MarkInviteAccepted(ctx context.Context, arg MarkInviteAcceptedParams) error {
	_, err := q.db.Exec(ctx, markInviteAccepted, arg.ID, arg.AcceptedBy)
	return err
}

const revokeInvite = `-- name: RevokeInvite :exec
UPDATE workspace_invites
SET revoked_at = now(), revoked_by = $2
WHERE id = $1
  AND accepted_at IS NULL
  AND revoked_at IS NULL
`

type RevokeInviteParams struct {
	ID        int64
	RevokedBy *int64
}

// Admin path. RLS gate on workspace + role applies.
func (q *Queries) RevokeInvite(ctx context.Context, arg RevokeInviteParams) error {
	_, err := q.db.Exec(ctx, revokeInvite, arg.ID, arg.RevokedBy)
	return err
}
