// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meetings.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpMeetingParticipantCount = `-- name: BumpMeetingParticipantCount :exec
UPDATE meetings SET participant_count = participant_count + 1 WHERE id = $1
`

// Called when a participant joins. Best-effort counter; actual truth is
// in LiveKit. Used for analytics + "was this a 1:1 or a group call".
func (q *Queries) BumpMeetingParticipantCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, bumpMeetingParticipantCount, id)
	return err
}

const createDMChannel = `-- name: CreateDMChannel :one
INSERT INTO channels (workspace_id, type, name, topic, description, default_join, created_by)
VALUES ($1, 'dm', NULL, '', '', false, $2)
RETURNING id, workspace_id, type, name, topic, description, default_join, created_by, created_at, updated_at, archived_at
`

type CreateDMChannelParams struct {
	WorkspaceID int64
	CreatedBy   *int64
}

// Helper for the find-or-create tx: creates the underlying channel row
// with type='dm' and NULL name (DMs don't get human-readable names).
func (q *Queries) CreateDMChannel(ctx context.Context, arg CreateDMChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createDMChannel, arg.WorkspaceID, arg.CreatedBy)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Type,
		&i.Name,
		&i.Topic,
		&i.Description,
		&i.DefaultJoin,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const createMeeting = `-- name: CreateMeeting :one


INSERT INTO meetings (workspace_id, channel_id, livekit_room, started_by, metadata)
VALUES ($1, $2, $3, $4, COALESCE($5::jsonb, '{}'::jsonb))
RETURNING id, workspace_id, channel_id, event_id, livekit_room, started_by, started_at, ended_at, ended_by, recording_file_id, participant_count, metadata
`

type CreateMeetingParams struct {
	WorkspaceID int64
	ChannelID   int64
	LivekitRoom string
	StartedBy   *int64
	Column5     []byte
}

// Meeting + DM queries (M8).
// ---- meetings -----------------------------------------------------------
// A new call instance on a channel. RLS enforces workspace scope.
func (q *Queries) CreateMeeting(ctx context.Context, arg CreateMeetingParams) (Meeting, error) {
	row := q.db.QueryRow(ctx, createMeeting,
		arg.WorkspaceID,
		arg.ChannelID,
		arg.LivekitRoom,
		arg.StartedBy,
		arg.Column5,
	)
	var i Meeting
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ChannelID,
		&i.EventID,
		&i.LivekitRoom,
		&i.StartedBy,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndedBy,
		&i.RecordingFileID,
		&i.ParticipantCount,
		&i.Metadata,
	)
	return i, err
}

const endMeeting = `-- name: EndMeeting :one
UPDATE meetings
SET ended_at = COALESCE(ended_at, now()),
    ended_by = COALESCE(ended_by, $2)
WHERE id = $1
RETURNING id, workspace_id, channel_id, event_id, livekit_room, started_by, started_at, ended_at, ended_by, recording_file_id, participant_count, metadata
`

type EndMeetingParams struct {
	ID      int64
	EndedBy *int64
}

// Idempotent — re-ending a meeting is a no-op that returns the same row.
func (q *Queries) EndMeeting(ctx context.Context, arg EndMeetingParams) (Meeting, error) {
	row := q.db.QueryRow(ctx, endMeeting, arg.ID, arg.EndedBy)
	var i Meeting
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ChannelID,
		&i.EventID,
		&i.LivekitRoom,
		&i.StartedBy,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndedBy,
		&i.RecordingFileID,
		&i.ParticipantCount,
		&i.Metadata,
	)
	return i, err
}

const findOrCreateDMChannel = `-- name: FindOrCreateDMChannel :one

INSERT INTO dm_pairs (workspace_id, user_a, user_b, channel_id)
VALUES (
    $1::bigint,
    LEAST($2::bigint, $3::bigint),
    GREATEST($2::bigint, $3::bigint),
    $4::bigint
)
ON CONFLICT (workspace_id, user_a, user_b)
DO UPDATE SET channel_id = dm_pairs.channel_id    -- no-op, to force RETURNING
RETURNING id, workspace_id, user_a, user_b, channel_id, created_at
`

type FindOrCreateDMChannelParams struct {
	WorkspaceID int64
	SelfID      int64
	OtherID     int64
	ChannelID   int64
}

// ---- DMs ---------------------------------------------------------------
// Create-or-return the DM channel for (current_user, other_user) in the
// current workspace. The handler wraps this in a tx that also:
//   - creates the channels row (type='dm', name=NULL)
//   - inserts channel_memberships rows for both users
//
// and only then calls this query to record the pair index.
//
// UPSERT semantics: if the pair already exists, we return the existing
// row (the handler uses RETURNING to discover whether it was a hit).
func (q *Queries) FindOrCreateDMChannel(ctx context.Context, arg FindOrCreateDMChannelParams) (DmPair, error) {
	row := q.db.QueryRow(ctx, findOrCreateDMChannel,
		arg.WorkspaceID,
		arg.SelfID,
		arg.OtherID,
		arg.ChannelID,
	)
	var i DmPair
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserA,
		&i.UserB,
		&i.ChannelID,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveMeetingForChannel = `-- name: GetActiveMeetingForChannel :one
SELECT id, workspace_id, channel_id, event_id, livekit_room, started_by, started_at, ended_at, ended_by, recording_file_id, participant_count, metadata FROM meetings
WHERE channel_id = $1 AND ended_at IS NULL
ORDER BY started_at DESC
LIMIT 1
`

// "Is there a call in progress on this channel?" Returns at most one row;
// the partial index backs the lookup.
func (q *Queries) GetActiveMeetingForChannel(ctx context.Context, channelID int64) (Meeting, error) {
	row := q.db.QueryRow(ctx, getActiveMeetingForChannel, channelID)
	var i Meeting
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ChannelID,
		&i.EventID,
		&i.LivekitRoom,
		&i.StartedBy,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndedBy,
		&i.RecordingFileID,
		&i.ParticipantCount,
		&i.Metadata,
	)
	return i, err
}

const getDMChannelForPair = `-- name: GetDMChannelForPair :one
SELECT id, workspace_id, user_a, user_b, channel_id, created_at FROM dm_pairs
WHERE workspace_id = $1::bigint
  AND user_a = LEAST($2::bigint, $3::bigint)
  AND user_b = GREATEST($2::bigint, $3::bigint)
`

type GetDMChannelForPairParams struct {
	WorkspaceID int64
	SelfID      int64
	OtherID     int64
}

// Read-side lookup. Returns zero rows when no DM exists yet; the handler
// treats that as "create one".
func (q *Queries) GetDMChannelForPair(ctx context.Context, arg GetDMChannelForPairParams) (DmPair, error) {
	row := q.db.QueryRow(ctx, getDMChannelForPair, arg.WorkspaceID, arg.SelfID, arg.OtherID)
	var i DmPair
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserA,
		&i.UserB,
		&i.ChannelID,
		&i.CreatedAt,
	)
	return i, err
}

const getMeetingByID = `-- name: GetMeetingByID :one
SELECT id, workspace_id, channel_id, event_id, livekit_room, started_by, started_at, ended_at, ended_by, recording_file_id, participant_count, metadata FROM meetings WHERE id = $1
`

func (q *Queries) GetMeetingByID(ctx context.Context, id int64) (Meeting, error) {
	row := q.db.QueryRow(ctx, getMeetingByID, id)
	var i Meeting
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ChannelID,
		&i.EventID,
		&i.LivekitRoom,
		&i.StartedBy,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndedBy,
		&i.RecordingFileID,
		&i.ParticipantCount,
		&i.Metadata,
	)
	return i, err
}

const listDMChannelsForUser = `-- name: ListDMChannelsForUser :many
SELECT
    p.id AS pair_id,
    c.id AS channel_id,
    c.type AS channel_type,
    c.created_at AS channel_created_at,
    (CASE WHEN p.user_a = $1::bigint THEN p.user_b ELSE p.user_a END)::bigint AS other_user_id,
    u.display_name AS other_display_name,
    u.email        AS other_email
FROM dm_pairs p
JOIN channels  c ON c.id = p.channel_id
JOIN users     u ON u.id = (CASE WHEN p.user_a = $1::bigint THEN p.user_b ELSE p.user_a END)::bigint
WHERE p.workspace_id = $2::bigint
  AND (p.user_a = $1::bigint OR p.user_b = $1::bigint)
  AND c.archived_at IS NULL
ORDER BY c.created_at DESC
`

type ListDMChannelsForUserParams struct {
	UserID      int64
	WorkspaceID int64
}

type ListDMChannelsForUserRow struct {
	PairID           int64
	ChannelID        int64
	ChannelType      string
	ChannelCreatedAt pgtype.Timestamptz
	OtherUserID      int64
	OtherDisplayName string
	OtherEmail       string
}

// Every DM this user is a part of in the workspace, plus the "other" user
// id so the UI can render the counterpart's name without a second query.
// The CASE outputs are explicitly cast so sqlc types them as bigint
// rather than interface{}.
func (q *Queries) ListDMChannelsForUser(ctx context.Context, arg ListDMChannelsForUserParams) ([]ListDMChannelsForUserRow, error) {
	rows, err := q.db.Query(ctx, listDMChannelsForUser, arg.UserID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDMChannelsForUserRow{}
	for rows.Next() {
		var i ListDMChannelsForUserRow
		if err := rows.Scan(
			&i.PairID,
			&i.ChannelID,
			&i.ChannelType,
			&i.ChannelCreatedAt,
			&i.OtherUserID,
			&i.OtherDisplayName,
			&i.OtherEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMeetingLiveKitRoom = `-- name: SetMeetingLiveKitRoom :exec
UPDATE meetings SET livekit_room = $2 WHERE id = $1
`

type SetMeetingLiveKitRoomParams struct {
	ID          int64
	LivekitRoom string
}

// Stamp the canonical LiveKit room name after we know the meeting id.
// Room names are derived from the id, so we assign sequentially.
func (q *Queries) SetMeetingLiveKitRoom(ctx context.Context, arg SetMeetingLiveKitRoomParams) error {
	_, err := q.db.Exec(ctx, setMeetingLiveKitRoom, arg.ID, arg.LivekitRoom)
	return err
}
