// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMembership = `-- name: CreateMembership :one
INSERT INTO workspace_memberships (workspace_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, workspace_id, user_id, role, custom_status, joined_at, deactivated_at, notify_pref
`

type CreateMembershipParams struct {
	WorkspaceID int64
	UserID      int64
	Role        string
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (WorkspaceMembership, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.WorkspaceID, arg.UserID, arg.Role)
	var i WorkspaceMembership
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CustomStatus,
		&i.JoinedAt,
		&i.DeactivatedAt,
		&i.NotifyPref,
	)
	return i, err
}

const deactivateMembership = `-- name: DeactivateMembership :exec
UPDATE workspace_memberships
SET deactivated_at = now()
WHERE workspace_id = $1 AND user_id = $2
`

type DeactivateMembershipParams struct {
	WorkspaceID int64
	UserID      int64
}

func (q *Queries) DeactivateMembership(ctx context.Context, arg DeactivateMembershipParams) error {
	_, err := q.db.Exec(ctx, deactivateMembership, arg.WorkspaceID, arg.UserID)
	return err
}

const getMembershipForUser = `-- name: GetMembershipForUser :one
SELECT id, workspace_id, user_id, role, custom_status, joined_at, deactivated_at, notify_pref FROM workspace_memberships
WHERE workspace_id = $1 AND user_id = $2 AND deactivated_at IS NULL
`

type GetMembershipForUserParams struct {
	WorkspaceID int64
	UserID      int64
}

func (q *Queries) GetMembershipForUser(ctx context.Context, arg GetMembershipForUserParams) (WorkspaceMembership, error) {
	row := q.db.QueryRow(ctx, getMembershipForUser, arg.WorkspaceID, arg.UserID)
	var i WorkspaceMembership
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CustomStatus,
		&i.JoinedAt,
		&i.DeactivatedAt,
		&i.NotifyPref,
	)
	return i, err
}

const listWorkspaceMembers = `-- name: ListWorkspaceMembers :many
SELECT m.id, m.workspace_id, m.user_id, m.role, m.custom_status, m.joined_at, m.deactivated_at, m.notify_pref, u.email, u.display_name, u.email_verified_at
FROM workspace_memberships m
JOIN users u ON u.id = m.user_id
WHERE m.workspace_id = $1 AND m.deactivated_at IS NULL
ORDER BY m.joined_at
`

type ListWorkspaceMembersRow struct {
	ID              int64
	WorkspaceID     int64
	UserID          int64
	Role            string
	CustomStatus    []byte
	JoinedAt        pgtype.Timestamptz
	DeactivatedAt   pgtype.Timestamptz
	NotifyPref      string
	Email           string
	DisplayName     string
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) ListWorkspaceMembers(ctx context.Context, workspaceID int64) ([]ListWorkspaceMembersRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceMembersRow{}
	for rows.Next() {
		var i ListWorkspaceMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.CustomStatus,
			&i.JoinedAt,
			&i.DeactivatedAt,
			&i.NotifyPref,
			&i.Email,
			&i.DisplayName,
			&i.EmailVerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMembershipCustomStatus = `-- name: UpdateMembershipCustomStatus :one
UPDATE workspace_memberships
SET custom_status = $3::jsonb
WHERE workspace_id = $1 AND user_id = $2
RETURNING id, workspace_id, user_id, role, custom_status, joined_at, deactivated_at, notify_pref
`

type UpdateMembershipCustomStatusParams struct {
	WorkspaceID int64
	UserID      int64
	Column3     []byte
}

// Caller sets custom_status to arbitrary JSONB. Pass '{}'::jsonb to clear.
// RLS on workspace_memberships allows this because the modify policy
// lets a user update their own rows (user_id match), so app.workspace_id
// does not need to be set on this path.
func (q *Queries) UpdateMembershipCustomStatus(ctx context.Context, arg UpdateMembershipCustomStatusParams) (WorkspaceMembership, error) {
	row := q.db.QueryRow(ctx, updateMembershipCustomStatus, arg.WorkspaceID, arg.UserID, arg.Column3)
	var i WorkspaceMembership
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CustomStatus,
		&i.JoinedAt,
		&i.DeactivatedAt,
		&i.NotifyPref,
	)
	return i, err
}

const updateMembershipNotifyPref = `-- name: UpdateMembershipNotifyPref :one
UPDATE workspace_memberships
SET notify_pref = $3
WHERE workspace_id = $1 AND user_id = $2
RETURNING id, workspace_id, user_id, role, custom_status, joined_at, deactivated_at, notify_pref
`

type UpdateMembershipNotifyPrefParams struct {
	WorkspaceID int64
	UserID      int64
	NotifyPref  string
}

// Workspace-level notification default. Same RLS story as custom_status:
// the user is updating their own row, which the wsm_modify policy permits.
func (q *Queries) UpdateMembershipNotifyPref(ctx context.Context, arg UpdateMembershipNotifyPrefParams) (WorkspaceMembership, error) {
	row := q.db.QueryRow(ctx, updateMembershipNotifyPref, arg.WorkspaceID, arg.UserID, arg.NotifyPref)
	var i WorkspaceMembership
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CustomStatus,
		&i.JoinedAt,
		&i.DeactivatedAt,
		&i.NotifyPref,
	)
	return i, err
}

const updateMembershipRole = `-- name: UpdateMembershipRole :exec
UPDATE workspace_memberships
SET role = $3
WHERE workspace_id = $1 AND user_id = $2
`

type UpdateMembershipRoleParams struct {
	WorkspaceID int64
	UserID      int64
	Role        string
}

func (q *Queries) UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) error {
	_, err := q.db.Exec(ctx, updateMembershipRole, arg.WorkspaceID, arg.UserID, arg.Role)
	return err
}
