// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mentions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMention = `-- name: CreateMention :exec
INSERT INTO mentions (workspace_id, channel_id, message_id, message_created_at, mentioned_user_id, author_user_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateMentionParams struct {
	WorkspaceID      int64
	ChannelID        int64
	MessageID        int64
	MessageCreatedAt pgtype.Timestamptz
	MentionedUserID  int64
	AuthorUserID     *int64
}

func (q *Queries) CreateMention(ctx context.Context, arg CreateMentionParams) error {
	_, err := q.db.Exec(ctx, createMention,
		arg.WorkspaceID,
		arg.ChannelID,
		arg.MessageID,
		arg.MessageCreatedAt,
		arg.MentionedUserID,
		arg.AuthorUserID,
	)
	return err
}

const listMyMentions = `-- name: ListMyMentions :many
SELECT id, workspace_id, channel_id, message_id, message_created_at, mentioned_user_id, author_user_id, created_at FROM mentions
WHERE mentioned_user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListMyMentionsParams struct {
	MentionedUserID int64
	Limit           int32
}

// Most-recent mentions for the current user, across all workspaces they
// belong to. The RLS policy on mentions limits rows to those where
// mentioned_user_id = app.user_id, so no explicit WHERE clause needed.
func (q *Queries) ListMyMentions(ctx context.Context, arg ListMyMentionsParams) ([]Mention, error) {
	rows, err := q.db.Query(ctx, listMyMentions, arg.MentionedUserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mention{}
	for rows.Next() {
		var i Mention
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ChannelID,
			&i.MessageID,
			&i.MessageCreatedAt,
			&i.MentionedUserID,
			&i.AuthorUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
