// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addReaction = `-- name: AddReaction :exec
INSERT INTO message_reactions (message_id, user_id, emoji, workspace_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type AddReactionParams struct {
	MessageID   int64
	UserID      int64
	Emoji       string
	WorkspaceID int64
}

func (q *Queries) AddReaction(ctx context.Context, arg AddReactionParams) error {
	_, err := q.db.Exec(ctx, addReaction,
		arg.MessageID,
		arg.UserID,
		arg.Emoji,
		arg.WorkspaceID,
	)
	return err
}

const countThreadReplies = `-- name: CountThreadReplies :one
SELECT count(*)::bigint AS n
FROM messages
WHERE thread_root_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountThreadReplies(ctx context.Context, threadRootID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, countThreadReplies, threadRootID)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (workspace_id, channel_id, author_user_id, body_md, body_blocks, thread_root_id, parent_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workspace_id, channel_id, thread_root_id, parent_id, author_user_id, author_bot_id, body_md, body_blocks, edited_at, deleted_at, created_at
`

type CreateMessageParams struct {
	WorkspaceID  int64
	ChannelID    int64
	AuthorUserID *int64
	BodyMd       string
	BodyBlocks   []byte
	ThreadRootID *int64
	ParentID     *int64
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.WorkspaceID,
		arg.ChannelID,
		arg.AuthorUserID,
		arg.BodyMd,
		arg.BodyBlocks,
		arg.ThreadRootID,
		arg.ParentID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ChannelID,
		&i.ThreadRootID,
		&i.ParentID,
		&i.AuthorUserID,
		&i.AuthorBotID,
		&i.BodyMd,
		&i.BodyBlocks,
		&i.EditedAt,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, workspace_id, channel_id, thread_root_id, parent_id, author_user_id, author_bot_id, body_md, body_blocks, edited_at, deleted_at, created_at FROM messages
WHERE id = $1
  AND created_at >= $2
  AND deleted_at IS NULL
`

type GetMessageByIDParams struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
}

// Bounded by (id, created_at) window so the query is partition-prunable.
// Callers who only have the id should use a short recency window here.
func (q *Queries) GetMessageByID(ctx context.Context, arg GetMessageByIDParams) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, arg.ID, arg.CreatedAt)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ChannelID,
		&i.ThreadRootID,
		&i.ParentID,
		&i.AuthorUserID,
		&i.AuthorBotID,
		&i.BodyMd,
		&i.BodyBlocks,
		&i.EditedAt,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listChannelMessages = `-- name: ListChannelMessages :many
SELECT m.id, m.workspace_id, m.channel_id, m.thread_root_id, m.parent_id, m.author_user_id, m.author_bot_id, m.body_md, m.body_blocks, m.edited_at, m.deleted_at, m.created_at,
       COALESCE(
         (SELECT count(*)::bigint
          FROM messages r
          WHERE r.thread_root_id = m.id
            AND r.deleted_at IS NULL),
         0::bigint
       )::bigint AS reply_count
FROM messages m
WHERE m.channel_id = $1
  AND m.deleted_at IS NULL
  AND m.thread_root_id IS NULL
  AND (
        $2::timestamptz IS NULL
     OR (m.created_at, m.id) < ($2::timestamptz, $3::bigint)
  )
ORDER BY m.created_at DESC, m.id DESC
LIMIT $4
`

type ListChannelMessagesParams struct {
	ChannelID int64
	Column2   pgtype.Timestamptz
	Column3   int64
	Limit     int32
}

type ListChannelMessagesRow struct {
	ID           int64
	WorkspaceID  int64
	ChannelID    int64
	ThreadRootID *int64
	ParentID     *int64
	AuthorUserID *int64
	AuthorBotID  *int64
	BodyMd       string
	BodyBlocks   []byte
	EditedAt     pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	ReplyCount   int64
}

// Reverse-chronological page through top-level channel messages (thread
// replies are fetched separately via ListThreadReplies). Cursor is
// (cursor_created_at, cursor_id) so the result is stable under concurrent
// inserts at the head of the channel.
func (q *Queries) ListChannelMessages(ctx context.Context, arg ListChannelMessagesParams) ([]ListChannelMessagesRow, error) {
	rows, err := q.db.Query(ctx, listChannelMessages,
		arg.ChannelID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChannelMessagesRow{}
	for rows.Next() {
		var i ListChannelMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ChannelID,
			&i.ThreadRootID,
			&i.ParentID,
			&i.AuthorUserID,
			&i.AuthorBotID,
			&i.BodyMd,
			&i.BodyBlocks,
			&i.EditedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.ReplyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReactionsForMessages = `-- name: ListReactionsForMessages :many
SELECT message_id, emoji,
       array_agg(user_id ORDER BY user_id)::bigint[] AS user_ids
FROM message_reactions
WHERE message_id = ANY($1::bigint[])
GROUP BY message_id, emoji
`

type ListReactionsForMessagesRow struct {
	MessageID int64
	Emoji     string
	UserIds   []int64
}

// Aggregates reactions for a batch of messages so the list endpoint can
// hydrate the page in a single round-trip. The explicit cast on array_agg
// lets sqlc infer []int64 instead of interface{}.
func (q *Queries) ListReactionsForMessages(ctx context.Context, dollar_1 []int64) ([]ListReactionsForMessagesRow, error) {
	rows, err := q.db.Query(ctx, listReactionsForMessages, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReactionsForMessagesRow{}
	for rows.Next() {
		var i ListReactionsForMessagesRow
		if err := rows.Scan(&i.MessageID, &i.Emoji, &i.UserIds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadReplies = `-- name: ListThreadReplies :many
SELECT id, workspace_id, channel_id, thread_root_id, parent_id, author_user_id, author_bot_id, body_md, body_blocks, edited_at, deleted_at, created_at FROM messages
WHERE thread_root_id = $1
  AND deleted_at IS NULL
  AND created_at >= $2
ORDER BY created_at ASC, id ASC
`

type ListThreadRepliesParams struct {
	ThreadRootID *int64
	CreatedAt    pgtype.Timestamptz
}

// Every reply under a thread root, oldest first. Root is NOT included.
func (q *Queries) ListThreadReplies(ctx context.Context, arg ListThreadRepliesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listThreadReplies, arg.ThreadRootID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ChannelID,
			&i.ThreadRootID,
			&i.ParentID,
			&i.AuthorUserID,
			&i.AuthorBotID,
			&i.BodyMd,
			&i.BodyBlocks,
			&i.EditedAt,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupWorkspaceMembersByIDs = `-- name: LookupWorkspaceMembersByIDs :many
SELECT m.user_id, u.display_name, u.email
FROM workspace_memberships m
JOIN users u ON u.id = m.user_id
WHERE m.workspace_id = $1
  AND m.user_id = ANY($2::bigint[])
  AND m.deactivated_at IS NULL
`

type LookupWorkspaceMembersByIDsParams struct {
	WorkspaceID int64
	Column2     []int64
}

type LookupWorkspaceMembersByIDsRow struct {
	UserID      int64
	DisplayName string
	Email       string
}

// Used to validate that a list of <@N> mention targets are actually in
// the current workspace before persisting mention rows.
func (q *Queries) LookupWorkspaceMembersByIDs(ctx context.Context, arg LookupWorkspaceMembersByIDsParams) ([]LookupWorkspaceMembersByIDsRow, error) {
	rows, err := q.db.Query(ctx, lookupWorkspaceMembersByIDs, arg.WorkspaceID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LookupWorkspaceMembersByIDsRow{}
	for rows.Next() {
		var i LookupWorkspaceMembersByIDsRow
		if err := rows.Scan(&i.UserID, &i.DisplayName, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeReaction = `-- name: RemoveReaction :exec
DELETE FROM message_reactions
WHERE message_id = $1 AND user_id = $2 AND emoji = $3
`

type RemoveReactionParams struct {
	MessageID int64
	UserID    int64
	Emoji     string
}

func (q *Queries) RemoveReaction(ctx context.Context, arg RemoveReactionParams) error {
	_, err := q.db.Exec(ctx, removeReaction, arg.MessageID, arg.UserID, arg.Emoji)
	return err
}

const softDeleteMessage = `-- name: SoftDeleteMessage :one
UPDATE messages
SET deleted_at = now()
WHERE id = $1
  AND created_at >= $2
  AND deleted_at IS NULL
RETURNING id, workspace_id, channel_id, thread_root_id, parent_id, author_user_id, author_bot_id, body_md, body_blocks, edited_at, deleted_at, created_at
`

type SoftDeleteMessageParams struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) SoftDeleteMessage(ctx context.Context, arg SoftDeleteMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, softDeleteMessage, arg.ID, arg.CreatedAt)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ChannelID,
		&i.ThreadRootID,
		&i.ParentID,
		&i.AuthorUserID,
		&i.AuthorBotID,
		&i.BodyMd,
		&i.BodyBlocks,
		&i.EditedAt,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateMessageBody = `-- name: UpdateMessageBody :one
UPDATE messages
SET body_md    = $3,
    body_blocks = $4,
    edited_at   = now()
WHERE id = $1
  AND created_at >= $2
RETURNING id, workspace_id, channel_id, thread_root_id, parent_id, author_user_id, author_bot_id, body_md, body_blocks, edited_at, deleted_at, created_at
`

type UpdateMessageBodyParams struct {
	ID         int64
	CreatedAt  pgtype.Timestamptz
	BodyMd     string
	BodyBlocks []byte
}

func (q *Queries) UpdateMessageBody(ctx context.Context, arg UpdateMessageBodyParams) (Message, error) {
	row := q.db.QueryRow(ctx, updateMessageBody,
		arg.ID,
		arg.CreatedAt,
		arg.BodyMd,
		arg.BodyBlocks,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ChannelID,
		&i.ThreadRootID,
		&i.ParentID,
		&i.AuthorUserID,
		&i.AuthorBotID,
		&i.BodyMd,
		&i.BodyBlocks,
		&i.EditedAt,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}
