// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type App struct {
	ID               int64
	Slug             string
	Name             string
	Description      string
	OwnerUserID      int64
	AvatarFileID     *int64
	Manifest         []byte
	ClientID         string
	ClientSecretHash string
	IsPublic         bool
	CreatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type AppInstallation struct {
	ID          int64
	AppID       int64
	WorkspaceID int64
	InstalledBy *int64
	Scopes      []byte
	BotUserID   *int64
	CreatedAt   pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
}

type AppOauthCode struct {
	Code                string
	AppID               int64
	WorkspaceID         int64
	UserID              int64
	RedirectUri         string
	Scopes              []byte
	CodeChallenge       string
	CodeChallengeMethod string
	ExpiresAt           pgtype.Timestamptz
	UsedAt              pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
}

type AppToken struct {
	TokenID           int64
	AppInstallationID int64
	WorkspaceID       int64
	TokenHash         string
	Label             string
	Scopes            []byte
	CreatedAt         pgtype.Timestamptz
	LastUsedAt        pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
}

type AuditLog struct {
	ID          int64
	WorkspaceID *int64
	ActorUserID *int64
	ActorIp     *netip.Addr
	Action      string
	TargetKind  *string
	TargetID    *string
	Metadata    []byte
	CreatedAt   pgtype.Timestamptz
}

type AuthToken struct {
	ID         int64
	UserID     int64
	Purpose    string
	TokenHash  []byte
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
	Ip         *netip.Addr
}

type Channel struct {
	ID          int64
	WorkspaceID int64
	Type        string
	Name        *string
	Topic       string
	Description string
	DefaultJoin bool
	CreatedBy   *int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	ArchivedAt  pgtype.Timestamptz
}

type ChannelMembership struct {
	ID                int64
	WorkspaceID       int64
	ChannelID         int64
	UserID            int64
	NotifyPref        string
	LastReadMessageID *int64
	JoinedAt          pgtype.Timestamptz
	MutedUntil        pgtype.Timestamptz
}

type DmPair struct {
	ID          int64
	WorkspaceID int64
	UserA       int64
	UserB       int64
	ChannelID   int64
	CreatedAt   pgtype.Timestamptz
}

type Event struct {
	ID               int64
	WorkspaceID      int64
	ChannelID        *int64
	Title            string
	Description      string
	LocationUrl      string
	StartAt          pgtype.Timestamptz
	EndAt            pgtype.Timestamptz
	TimeZone         string
	Rrule            *string
	RecordingEnabled bool
	VideoEnabled     bool
	CreatedBy        *int64
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	CanceledAt       pgtype.Timestamptz
	ExternalProvider *string
	ExternalEventID  *string
	ExternalEtag     *string
}

type EventAttendee struct {
	ID            int64
	EventID       int64
	UserID        *int64
	ExternalEmail *string
	Rsvp          string
	InvitedAt     pgtype.Timestamptz
	RespondedAt   pgtype.Timestamptz
}

type ExternalCalendar struct {
	ID                   int64
	UserID               int64
	Provider             string
	ExternalAccountEmail string
	OauthRefreshToken    string
	SyncToken            *string
	SyncStatus           []byte
	LastSyncedAt         pgtype.Timestamptz
	ConnectedAt          pgtype.Timestamptz
	DisconnectedAt       pgtype.Timestamptz
}

type File struct {
	ID             int64
	WorkspaceID    int64
	UploaderUserID *int64
	StorageBackend string
	StorageKey     string
	Filename       string
	Mime           string
	SizeBytes      int64
	Sha256         string
	ScanStatus     string
	Derivatives    []byte
	Width          *int32
	Height         *int32
	CreatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type InstallSetting struct {
	Key       string
	Value     string
	Encrypted bool
	UpdatedAt pgtype.Timestamptz
	UpdatedBy *int64
}

type Meeting struct {
	ID               int64
	WorkspaceID      int64
	ChannelID        int64
	EventID          *int64
	LivekitRoom      string
	StartedBy        *int64
	StartedAt        pgtype.Timestamptz
	EndedAt          pgtype.Timestamptz
	EndedBy          *int64
	RecordingFileID  *int64
	ParticipantCount int32
	Metadata         []byte
}

type Mention struct {
	ID               int64
	WorkspaceID      int64
	ChannelID        int64
	MessageID        int64
	MessageCreatedAt pgtype.Timestamptz
	MentionedUserID  int64
	AuthorUserID     *int64
	CreatedAt        pgtype.Timestamptz
}

type Message struct {
	ID                      int64
	WorkspaceID             int64
	ChannelID               int64
	ThreadRootID            *int64
	ParentID                *int64
	AuthorUserID            *int64
	AuthorBotID             *int64
	BodyMd                  string
	BodyBlocks              []byte
	EditedAt                pgtype.Timestamptz
	DeletedAt               pgtype.Timestamptz
	CreatedAt               pgtype.Timestamptz
	AuthorBotInstallationID *int64
}

type MessageAttachment struct {
	ID          int64
	WorkspaceID int64
	ChannelID   int64
	MessageID   int64
	FileID      int64
	Position    int32
	CreatedAt   pgtype.Timestamptz
}

type MessageReaction struct {
	MessageID   int64
	UserID      int64
	Emoji       string
	WorkspaceID int64
	CreatedAt   pgtype.Timestamptz
}

type OauthIdentity struct {
	ID             int64
	UserID         int64
	Provider       string
	ProviderUserID string
	Raw            []byte
	CreatedAt      pgtype.Timestamptz
}

type Page struct {
	ID          int64
	WorkspaceID int64
	ChannelID   *int64
	Title       string
	DocID       string
	Icon        string
	CreatedBy   *int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	ArchivedAt  pgtype.Timestamptz
}

type PageComment struct {
	ID          int64
	PageID      int64
	WorkspaceID int64
	ParentID    *int64
	AuthorID    *int64
	Anchor      string
	BodyMd      string
	ResolvedAt  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type PageSnapshot struct {
	ID           int64
	PageID       int64
	WorkspaceID  int64
	SnapshotData []byte
	ByteSize     int32
	CreatedBy    *int64
	Reason       string
	CreatedAt    pgtype.Timestamptz
}

type SearchOutbox struct {
	ID          int64
	WorkspaceID int64
	Kind        string
	Action      string
	TargetID    int64
	Payload     []byte
	EnqueuedAt  pgtype.Timestamptz
	ProcessedAt pgtype.Timestamptz
	Attempts    int32
	LastError   *string
}

type Session struct {
	ID               int64
	UserID           int64
	WorkspaceID      *int64
	RefreshTokenHash []byte
	UserAgent        string
	Ip               *netip.Addr
	CreatedAt        pgtype.Timestamptz
	LastSeenAt       pgtype.Timestamptz
	ExpiresAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
}

type SlashCommand struct {
	ID                int64
	WorkspaceID       int64
	AppInstallationID int64
	Command           string
	TargetUrl         string
	Description       string
	UsageHint         string
	SigningSecretHash string
	CreatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
}

type User struct {
	ID                   int64
	Email                string
	PasswordHash         *string
	DisplayName          string
	AvatarFileID         *int64
	EmailVerifiedAt      pgtype.Timestamptz
	TotpSecret           *string
	LockedUntil          pgtype.Timestamptz
	FailedLoginCount     int32
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeactivatedAt        pgtype.Timestamptz
	DndEnabledUntil      pgtype.Timestamptz
	QuietHoursStart      *int32
	QuietHoursEnd        *int32
	QuietHoursTz         *string
	IsBot                bool
	BotAppInstallationID *int64
	IsSuperAdmin         bool
}

type UserDevice struct {
	ID             int64
	UserID         int64
	Platform       string
	Endpoint       string
	P256dh         string
	AuthSecret     string
	UserAgent      string
	Label          string
	CreatedAt      pgtype.Timestamptz
	LastSeenAt     pgtype.Timestamptz
	DisabledAt     pgtype.Timestamptz
	DisabledReason string
}

type WebhooksIncoming struct {
	ID                int64
	WorkspaceID       int64
	ChannelID         int64
	Name              string
	Token             string
	SigningSecretHash string
	CreatedBy         *int64
	CreatedAt         pgtype.Timestamptz
	LastUsedAt        pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
}

type WebhooksOutgoing struct {
	ID                int64
	WorkspaceID       int64
	AppInstallationID int64
	EventPattern      string
	TargetUrl         string
	SigningSecretHash string
	CreatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
}

type Workspace struct {
	ID            int64
	Slug          string
	Name          string
	Description   string
	BrandColor    *string
	LogoFileID    *int64
	RetentionDays *int32
	CreatedBy     int64
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	ArchivedAt    pgtype.Timestamptz
}

type WorkspaceEmailSetting struct {
	WorkspaceID     int64
	Provider        string
	ResendApiKeyEnc string
	FromAddress     string
	FromName        string
	UpdatedAt       pgtype.Timestamptz
	UpdatedBy       *int64
}

type WorkspaceInvite struct {
	ID          int64
	WorkspaceID int64
	Token       string
	Email       *string
	Role        string
	CreatedBy   int64
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	AcceptedAt  pgtype.Timestamptz
	AcceptedBy  *int64
	RevokedAt   pgtype.Timestamptz
	RevokedBy   *int64
}

type WorkspaceMembership struct {
	ID            int64
	WorkspaceID   int64
	UserID        int64
	Role          string
	CustomStatus  []byte
	JoinedAt      pgtype.Timestamptz
	DeactivatedAt pgtype.Timestamptz
	NotifyPref    string
}
