// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pages.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archivePage = `-- name: ArchivePage :exec
UPDATE pages SET archived_at = now() WHERE id = $1
`

func (q *Queries) ArchivePage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, archivePage, id)
	return err
}

const createPage = `-- name: CreatePage :one


INSERT INTO pages (workspace_id, channel_id, title, doc_id, icon, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, channel_id, title, doc_id, icon, created_by, created_at, updated_at, archived_at
`

type CreatePageParams struct {
	WorkspaceID int64
	ChannelID   *int64
	Title       string
	DocID       string
	Icon        string
	CreatedBy   *int64
}

// Native Pages (M10).
// ---- pages --------------------------------------------------------------
func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (Page, error) {
	row := q.db.QueryRow(ctx, createPage,
		arg.WorkspaceID,
		arg.ChannelID,
		arg.Title,
		arg.DocID,
		arg.Icon,
		arg.CreatedBy,
	)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ChannelID,
		&i.Title,
		&i.DocID,
		&i.Icon,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const createPageComment = `-- name: CreatePageComment :one

INSERT INTO page_comments (page_id, workspace_id, parent_id, author_id, anchor, body_md)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, page_id, workspace_id, parent_id, author_id, anchor, body_md, resolved_at, created_at, updated_at, deleted_at
`

type CreatePageCommentParams struct {
	PageID      int64
	WorkspaceID int64
	ParentID    *int64
	AuthorID    *int64
	Anchor      string
	BodyMd      string
}

// ---- comments -----------------------------------------------------------
func (q *Queries) CreatePageComment(ctx context.Context, arg CreatePageCommentParams) (PageComment, error) {
	row := q.db.QueryRow(ctx, createPageComment,
		arg.PageID,
		arg.WorkspaceID,
		arg.ParentID,
		arg.AuthorID,
		arg.Anchor,
		arg.BodyMd,
	)
	var i PageComment
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.AuthorID,
		&i.Anchor,
		&i.BodyMd,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createPageSnapshot = `-- name: CreatePageSnapshot :one

INSERT INTO page_snapshots (page_id, workspace_id, snapshot_data, byte_size, created_by, reason)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, page_id, workspace_id, snapshot_data, byte_size, created_by, reason, created_at
`

type CreatePageSnapshotParams struct {
	PageID       int64
	WorkspaceID  int64
	SnapshotData []byte
	ByteSize     int32
	CreatedBy    *int64
	Reason       string
}

// ---- snapshots ----------------------------------------------------------
func (q *Queries) CreatePageSnapshot(ctx context.Context, arg CreatePageSnapshotParams) (PageSnapshot, error) {
	row := q.db.QueryRow(ctx, createPageSnapshot,
		arg.PageID,
		arg.WorkspaceID,
		arg.SnapshotData,
		arg.ByteSize,
		arg.CreatedBy,
		arg.Reason,
	)
	var i PageSnapshot
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.WorkspaceID,
		&i.SnapshotData,
		&i.ByteSize,
		&i.CreatedBy,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const deletePageComment = `-- name: DeletePageComment :exec
UPDATE page_comments SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeletePageComment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePageComment, id)
	return err
}

const getPageByDocID = `-- name: GetPageByDocID :one
SELECT id, workspace_id, channel_id, title, doc_id, icon, created_by, created_at, updated_at, archived_at FROM pages WHERE doc_id = $1
`

func (q *Queries) GetPageByDocID(ctx context.Context, docID string) (Page, error) {
	row := q.db.QueryRow(ctx, getPageByDocID, docID)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ChannelID,
		&i.Title,
		&i.DocID,
		&i.Icon,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getPageByID = `-- name: GetPageByID :one
SELECT id, workspace_id, channel_id, title, doc_id, icon, created_by, created_at, updated_at, archived_at FROM pages WHERE id = $1
`

func (q *Queries) GetPageByID(ctx context.Context, id int64) (Page, error) {
	row := q.db.QueryRow(ctx, getPageByID, id)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ChannelID,
		&i.Title,
		&i.DocID,
		&i.Icon,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getPageSnapshot = `-- name: GetPageSnapshot :one
SELECT id, page_id, workspace_id, snapshot_data, byte_size, created_by, reason, created_at FROM page_snapshots WHERE id = $1 AND page_id = $2
`

type GetPageSnapshotParams struct {
	ID     int64
	PageID int64
}

func (q *Queries) GetPageSnapshot(ctx context.Context, arg GetPageSnapshotParams) (PageSnapshot, error) {
	row := q.db.QueryRow(ctx, getPageSnapshot, arg.ID, arg.PageID)
	var i PageSnapshot
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.WorkspaceID,
		&i.SnapshotData,
		&i.ByteSize,
		&i.CreatedBy,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const listPageComments = `-- name: ListPageComments :many
SELECT pc.id, pc.page_id, pc.workspace_id, pc.parent_id, pc.author_id, pc.anchor, pc.body_md, pc.resolved_at, pc.created_at, pc.updated_at, pc.deleted_at, u.display_name AS author_display_name
FROM   page_comments pc
LEFT JOIN users u ON u.id = pc.author_id
WHERE  pc.page_id = $1
  AND  pc.deleted_at IS NULL
ORDER BY pc.created_at ASC
`

type ListPageCommentsRow struct {
	ID                int64
	PageID            int64
	WorkspaceID       int64
	ParentID          *int64
	AuthorID          *int64
	Anchor            string
	BodyMd            string
	ResolvedAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	AuthorDisplayName *string
}

func (q *Queries) ListPageComments(ctx context.Context, pageID int64) ([]ListPageCommentsRow, error) {
	rows, err := q.db.Query(ctx, listPageComments, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPageCommentsRow{}
	for rows.Next() {
		var i ListPageCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.WorkspaceID,
			&i.ParentID,
			&i.AuthorID,
			&i.Anchor,
			&i.BodyMd,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.AuthorDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPageSnapshots = `-- name: ListPageSnapshots :many
SELECT ps.id, ps.page_id, ps.byte_size, ps.reason, ps.created_at,
       ps.created_by, u.display_name AS creator_display_name
FROM   page_snapshots ps
LEFT JOIN users u ON u.id = ps.created_by
WHERE  ps.page_id = $1
ORDER BY ps.created_at DESC
LIMIT  $2 OFFSET $3
`

type ListPageSnapshotsParams struct {
	PageID int64
	Limit  int32
	Offset int32
}

type ListPageSnapshotsRow struct {
	ID                 int64
	PageID             int64
	ByteSize           int32
	Reason             string
	CreatedAt          pgtype.Timestamptz
	CreatedBy          *int64
	CreatorDisplayName *string
}

func (q *Queries) ListPageSnapshots(ctx context.Context, arg ListPageSnapshotsParams) ([]ListPageSnapshotsRow, error) {
	rows, err := q.db.Query(ctx, listPageSnapshots, arg.PageID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPageSnapshotsRow{}
	for rows.Next() {
		var i ListPageSnapshotsRow
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.ByteSize,
			&i.Reason,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.CreatorDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPagesForChannel = `-- name: ListPagesForChannel :many
SELECT p.id, p.workspace_id, p.channel_id, p.title, p.doc_id, p.icon, p.created_by, p.created_at, p.updated_at, p.archived_at, u.display_name AS creator_display_name
FROM   pages p
LEFT JOIN users u ON u.id = p.created_by
WHERE  p.channel_id = $1
  AND  p.archived_at IS NULL
ORDER BY p.updated_at DESC
`

type ListPagesForChannelRow struct {
	ID                 int64
	WorkspaceID        int64
	ChannelID          *int64
	Title              string
	DocID              string
	Icon               string
	CreatedBy          *int64
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	ArchivedAt         pgtype.Timestamptz
	CreatorDisplayName *string
}

func (q *Queries) ListPagesForChannel(ctx context.Context, channelID *int64) ([]ListPagesForChannelRow, error) {
	rows, err := q.db.Query(ctx, listPagesForChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPagesForChannelRow{}
	for rows.Next() {
		var i ListPagesForChannelRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ChannelID,
			&i.Title,
			&i.DocID,
			&i.Icon,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.CreatorDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPagesForWorkspace = `-- name: ListPagesForWorkspace :many
SELECT p.id, p.workspace_id, p.channel_id, p.title, p.doc_id, p.icon, p.created_by, p.created_at, p.updated_at, p.archived_at, u.display_name AS creator_display_name
FROM   pages p
LEFT JOIN users u ON u.id = p.created_by
WHERE  p.workspace_id = $1
  AND  p.archived_at IS NULL
ORDER BY p.updated_at DESC
LIMIT  $2 OFFSET $3
`

type ListPagesForWorkspaceParams struct {
	WorkspaceID int64
	Limit       int32
	Offset      int32
}

type ListPagesForWorkspaceRow struct {
	ID                 int64
	WorkspaceID        int64
	ChannelID          *int64
	Title              string
	DocID              string
	Icon               string
	CreatedBy          *int64
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	ArchivedAt         pgtype.Timestamptz
	CreatorDisplayName *string
}

func (q *Queries) ListPagesForWorkspace(ctx context.Context, arg ListPagesForWorkspaceParams) ([]ListPagesForWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listPagesForWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPagesForWorkspaceRow{}
	for rows.Next() {
		var i ListPagesForWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ChannelID,
			&i.Title,
			&i.DocID,
			&i.Icon,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.CreatorDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneOldSnapshots = `-- name: PruneOldSnapshots :exec
DELETE FROM page_snapshots
WHERE id IN (
    SELECT ps.id
    FROM   page_snapshots ps
    WHERE  ps.page_id = $1
    ORDER BY ps.created_at DESC
    OFFSET $2
)
`

type PruneOldSnapshotsParams struct {
	PageID int64
	Offset int32
}

// Retention: keep at most $2 snapshots per page (newest first).
func (q *Queries) PruneOldSnapshots(ctx context.Context, arg PruneOldSnapshotsParams) error {
	_, err := q.db.Exec(ctx, pruneOldSnapshots, arg.PageID, arg.Offset)
	return err
}

const touchPage = `-- name: TouchPage :exec
UPDATE pages
SET updated_at = now()
WHERE id = $1
`

func (q *Queries) TouchPage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchPage, id)
	return err
}

const unarchivePage = `-- name: UnarchivePage :exec
UPDATE pages SET archived_at = NULL WHERE id = $1
`

func (q *Queries) UnarchivePage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, unarchivePage, id)
	return err
}

const updatePage = `-- name: UpdatePage :one
UPDATE pages
SET title      = COALESCE($1::text,   title),
    channel_id = $2::bigint,
    icon       = COALESCE($3::text,    icon),
    updated_at = now()
WHERE id = $4::bigint
RETURNING id, workspace_id, channel_id, title, doc_id, icon, created_by, created_at, updated_at, archived_at
`

type UpdatePageParams struct {
	Title     *string
	ChannelID *int64
	Icon      *string
	ID        int64
}

// Patch-style update. channel_id is always written: pass the current
// value (from GetPageByID) to leave it unchanged, or NULL to detach.
func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) (Page, error) {
	row := q.db.QueryRow(ctx, updatePage,
		arg.Title,
		arg.ChannelID,
		arg.Icon,
		arg.ID,
	)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ChannelID,
		&i.Title,
		&i.DocID,
		&i.Icon,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updatePageComment = `-- name: UpdatePageComment :one
UPDATE page_comments
SET body_md    = COALESCE($1::text, body_md),
    resolved_at = CASE
        WHEN $2::bool IS TRUE  THEN now()
        WHEN $2::bool IS FALSE THEN NULL
        ELSE resolved_at
    END,
    updated_at = now()
WHERE id = $3::bigint
RETURNING id, page_id, workspace_id, parent_id, author_id, anchor, body_md, resolved_at, created_at, updated_at, deleted_at
`

type UpdatePageCommentParams struct {
	BodyMd   *string
	Resolved *bool
	ID       int64
}

func (q *Queries) UpdatePageComment(ctx context.Context, arg UpdatePageCommentParams) (PageComment, error) {
	row := q.db.QueryRow(ctx, updatePageComment, arg.BodyMd, arg.Resolved, arg.ID)
	var i PageComment
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.AuthorID,
		&i.Anchor,
		&i.BodyMd,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
