// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	AddReaction(ctx context.Context, arg AddReactionParams) error
	ArchiveChannel(ctx context.Context, id int64) error
	ArchivePage(ctx context.Context, id int64) error
	ArchiveWorkspace(ctx context.Context, id int64) error
	// Called when a participant joins. Best-effort counter; actual truth is
	// in LiveKit. Used for analytics + "was this a 1:1 or a group call".
	BumpMeetingParticipantCount(ctx context.Context, id int64) error
	CancelEvent(ctx context.Context, id int64) error
	// Locks up to `limit` pending rows for this worker to process. FOR UPDATE
	// SKIP LOCKED lets multiple workers share the queue without serializing
	// on a single row. Rows with too many failures are skipped so one poison
	// message can't block the backlog; poison rows stay visible via the
	// idx_search_outbox_errors index for manual inspection.
	ClaimSearchOutboxBatch(ctx context.Context, arg ClaimSearchOutboxBatchParams) ([]ClaimSearchOutboxBatchRow, error)
	ConsumeAuthToken(ctx context.Context, id int64) error
	CountMentionsAfter(ctx context.Context, arg CountMentionsAfterParams) (int64, error)
	// Per-channel unread count. Partitioned messages; the created_at lower
	// bound is the message floor we care about.
	CountMessagesAfter(ctx context.Context, arg CountMessagesAfterParams) (int64, error)
	CountPendingSearchOutbox(ctx context.Context) (int64, error)
	CountRecentAuthTokens(ctx context.Context, arg CountRecentAuthTokensParams) (int64, error)
	CountThreadReplies(ctx context.Context, threadRootID *int64) (int64, error)
	CountWorkspacesForUser(ctx context.Context, userID int64) (int64, error)
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (MessageAttachment, error)
	CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) (AuthToken, error)
	CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error)
	CreateChannelMembership(ctx context.Context, arg CreateChannelMembershipParams) (ChannelMembership, error)
	// Helper for the find-or-create tx: creates the underlying channel row
	// with type='dm' and NULL name (DMs don't get human-readable names).
	CreateDMChannel(ctx context.Context, arg CreateDMChannelParams) (Channel, error)
	// Calendar events (M9).
	// ---- events ------------------------------------------------------------
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	// Meeting + DM queries (M8).
	// ---- meetings -----------------------------------------------------------
	// A new call instance on a channel. RLS enforces workspace scope.
	CreateMeeting(ctx context.Context, arg CreateMeetingParams) (Meeting, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (WorkspaceMembership, error)
	CreateMention(ctx context.Context, arg CreateMentionParams) error
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	// Native Pages (M10).
	// ---- pages --------------------------------------------------------------
	CreatePage(ctx context.Context, arg CreatePageParams) (Page, error)
	// ---- comments -----------------------------------------------------------
	CreatePageComment(ctx context.Context, arg CreatePageCommentParams) (PageComment, error)
	// ---- snapshots ----------------------------------------------------------
	CreatePageSnapshot(ctx context.Context, arg CreatePageSnapshotParams) (PageSnapshot, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	// Workspace invite queries (M7).
	//
	// Two call paths converge on this table:
	//
	//   Admin path (runtime pool, sliils_app role): create / list / revoke.
	//     Relies on the invites_modify + invites_select RLS policies in
	//     20260424000002_workspace_invites.sql — the admin must have the GUC
	//     app.workspace_id set to the right workspace.
	//
	//   Accept path (owner pool, RLS bypassed): lookup by token, mark accepted,
	//     create the workspace_membership. The token is the unguessable handle
	//     so we don't need tenant scope to look it up; we verify the accepting
	//     user's identity at the handler layer.
	// Called by the admin flow. RLS enforces that app.workspace_id matches
	// the row's workspace_id AND the caller is an owner/admin of that
	// workspace. Token is generated by the handler and passed in.
	CreateWorkspaceInvite(ctx context.Context, arg CreateWorkspaceInviteParams) (WorkspaceInvite, error)
	DeactivateMembership(ctx context.Context, arg DeactivateMembershipParams) error
	DeletePageComment(ctx context.Context, id int64) error
	DisconnectExternalCalendar(ctx context.Context, arg DisconnectExternalCalendarParams) error
	// Idempotent — re-ending a meeting is a no-op that returns the same row.
	EndMeeting(ctx context.Context, arg EndMeetingParams) (Meeting, error)
	// Search outbox + hydration queries (M6).
	//
	// Writes to the outbox happen inside message-mutation transactions (with
	// app.workspace_id set, so the tenant RLS policy applies). Reads / updates
	// from the drain worker use a privileged owner-pool that bypasses RLS —
	// see internal/db.OpenOwner.
	// Enqueues one search-index event. Must run inside the same tx as the
	// originating write so indexing state can never diverge from DB state.
	EnqueueSearchOutbox(ctx context.Context, arg EnqueueSearchOutboxParams) error
	// ---- DMs ---------------------------------------------------------------
	// Create-or-return the DM channel for (current_user, other_user) in the
	// current workspace. The handler wraps this in a tx that also:
	//   - creates the channels row (type='dm', name=NULL)
	//   - inserts channel_memberships rows for both users
	// and only then calls this query to record the pair index.
	//
	// UPSERT semantics: if the pair already exists, we return the existing
	// row (the handler uses RETURNING to discover whether it was a hit).
	FindOrCreateDMChannel(ctx context.Context, arg FindOrCreateDMChannelParams) (DmPair, error)
	// "Is there a call in progress on this channel?" Returns at most one row;
	// the partial index backs the lookup.
	GetActiveMeetingForChannel(ctx context.Context, channelID int64) (Meeting, error)
	GetAuthTokenByHash(ctx context.Context, arg GetAuthTokenByHashParams) (AuthToken, error)
	GetChannelByID(ctx context.Context, id int64) (Channel, error)
	GetChannelByName(ctx context.Context, arg GetChannelByNameParams) (Channel, error)
	GetChannelMembership(ctx context.Context, arg GetChannelMembershipParams) (ChannelMembership, error)
	// Read-side lookup. Returns zero rows when no DM exists yet; the handler
	// treats that as "create one".
	GetDMChannelForPair(ctx context.Context, arg GetDMChannelForPairParams) (DmPair, error)
	// Dedupe key during pull-from-Google sync. NULL provider/event_id never
	// matches (all the fields are enforced non-null by the UNIQUE index).
	GetEventByExternalID(ctx context.Context, arg GetEventByExternalIDParams) (Event, error)
	GetEventByID(ctx context.Context, id int64) (Event, error)
	GetExternalCalendar(ctx context.Context, arg GetExternalCalendarParams) (ExternalCalendar, error)
	GetFileByID(ctx context.Context, id int64) (File, error)
	// De-dupe lookup: if the same file content is uploaded twice to the same
	// workspace, point at the first record instead of creating a duplicate.
	GetFileBySHA256(ctx context.Context, arg GetFileBySHA256Params) (File, error)
	// Token lookup. Runs on the OWNER pool (RLS bypassed) so the accept path
	// can find the invite without knowing the workspace id. The handler
	// validates expiry + revoked + accepted + email-match server-side before
	// acting on the result.
	GetInviteByToken(ctx context.Context, token string) (GetInviteByTokenRow, error)
	GetMeetingByID(ctx context.Context, id int64) (Meeting, error)
	GetMembershipForUser(ctx context.Context, arg GetMembershipForUserParams) (WorkspaceMembership, error)
	// Bounded by (id, created_at) window so the query is partition-prunable.
	// Callers who only have the id should use a short recency window here.
	GetMessageByID(ctx context.Context, arg GetMessageByIDParams) (Message, error)
	// ---- hydration queries ----------------------------------------------------
	// Fetch the current state of a message plus the channel it lives in for
	// building a Meilisearch document. Runs on the owner pool — RLS bypassed.
	// The partition prune lower bound is expressed in months: the worker passes
	// a timestamp computed from the outbox enqueued_at minus a small slack
	// window so partition pruning still helps even if the indexer runs late.
	GetMessageForIndexing(ctx context.Context, arg GetMessageForIndexingParams) (GetMessageForIndexingRow, error)
	// ---- search-result hydration (runs under user's workspace GUC) ------------
	// Called by POST /search after Meilisearch returns a ranked list of message
	// ids. Uses the user's workspace + user GUCs so RLS double-checks visibility
	// — any stale doc whose membership was revoked between index-time and query-
	// time is silently dropped. Soft-deleted messages are also filtered out.
	GetMessagesByIDsForSearch(ctx context.Context, arg GetMessagesByIDsForSearchParams) ([]GetMessagesByIDsForSearchRow, error)
	GetPageByDocID(ctx context.Context, docID string) (Page, error)
	GetPageByID(ctx context.Context, id int64) (Page, error)
	GetPageSnapshot(ctx context.Context, arg GetPageSnapshotParams) (PageSnapshot, error)
	GetSessionByRefreshHash(ctx context.Context, refreshTokenHash []byte) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetWorkspaceByID(ctx context.Context, id int64) (Workspace, error)
	GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error)
	IncrementFailedLogins(ctx context.Context, arg IncrementFailedLoginsParams) (IncrementFailedLoginsRow, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	// Owner-pool path for the accept. Bypasses the workspace_memberships
	// RLS policy (which requires app.workspace_id to be set — we don't
	// set it here because the accepting user hasn't "selected" the workspace
	// in their session yet). Safe because the token lookup above already
	// proved the caller's right to enroll.
	InsertWorkspaceMembershipFromInvite(ctx context.Context, arg InsertWorkspaceMembershipFromInviteParams) (WorkspaceMembership, error)
	InvalidateActiveAuthTokens(ctx context.Context, arg InvalidateActiveAuthTokensParams) error
	// Used by the pull worker. Returns every active connection across every
	// user — owner pool only.
	ListActiveExternalCalendars(ctx context.Context) ([]ExternalCalendar, error)
	// Hydrates attachments for a batch of messages in a single query. Joined
	// against files so the client gets everything it needs to render a preview.
	ListAttachmentsForMessages(ctx context.Context, dollar_1 []int64) ([]ListAttachmentsForMessagesRow, error)
	ListAttendeesForEvent(ctx context.Context, eventID int64) ([]ListAttendeesForEventRow, error)
	// Returns every user id with an active channel membership. Used to bake
	// `channel_member_ids` into Meilisearch documents for private channels / DMs.
	ListChannelMemberIDs(ctx context.Context, channelID int64) ([]int64, error)
	// Reverse-chronological page through top-level channel messages (thread
	// replies are fetched separately via ListThreadReplies). Cursor is
	// (cursor_created_at, cursor_id) so the result is stable under concurrent
	// inserts at the head of the channel.
	ListChannelMessages(ctx context.Context, arg ListChannelMessagesParams) ([]ListChannelMessagesRow, error)
	// Every DM this user is a part of in the workspace, plus the "other" user
	// id so the UI can render the counterpart's name without a second query.
	// The CASE outputs are explicitly cast so sqlc types them as bigint
	// rather than interface{}.
	ListDMChannelsForUser(ctx context.Context, arg ListDMChannelsForUserParams) ([]ListDMChannelsForUserRow, error)
	ListEventsForChannel(ctx context.Context, channelID *int64) ([]Event, error)
	// Returns every non-canceled event whose "span" could intersect the
	// (from, to) window. RRULE expansion happens in Go — this just narrows
	// to candidate series by start_at.
	//
	// Why the generous upper bound on start_at? For a daily recurring event
	// whose root is in January, the caller might be asking for a May window.
	// Including events whose start_at is <= $3 (the window end) keeps the
	// candidate set tight enough while letting the RRULE expander produce
	// valid May instances.
	ListEventsInRange(ctx context.Context, arg ListEventsInRangeParams) ([]ListEventsInRangeRow, error)
	ListExternalCalendarsForUser(ctx context.Context, userID int64) ([]ExternalCalendar, error)
	// ---- bootstrap / full reindex --------------------------------------------
	// Streaming-style pagination for the initial / full reindex path. Returns
	// message ids newer than the cursor, capped at `limit`, so the caller can
	// iterate until empty. Excluded: soft-deleted messages (they'd be deleted
	// from the index anyway).
	ListMessageIDsForBackfill(ctx context.Context, arg ListMessageIDsForBackfillParams) ([]ListMessageIDsForBackfillRow, error)
	// Most-recent mentions for the current user, across all workspaces they
	// belong to. The RLS policy on mentions limits rows to those where
	// mentioned_user_id = app.user_id, so no explicit WHERE clause needed.
	ListMyMentions(ctx context.Context, arg ListMyMentionsParams) ([]Mention, error)
	ListPageComments(ctx context.Context, pageID int64) ([]ListPageCommentsRow, error)
	ListPageSnapshots(ctx context.Context, arg ListPageSnapshotsParams) ([]ListPageSnapshotsRow, error)
	ListPagesForChannel(ctx context.Context, channelID *int64) ([]ListPagesForChannelRow, error)
	ListPagesForWorkspace(ctx context.Context, arg ListPagesForWorkspaceParams) ([]ListPagesForWorkspaceRow, error)
	// Admin-facing list of outstanding invites. The partial index drives this.
	ListPendingInvitesForWorkspace(ctx context.Context, workspaceID int64) ([]ListPendingInvitesForWorkspaceRow, error)
	// Lists every non-archived public channel in the current workspace. Private
	// channels and DMs show up in M3 once channel_memberships exists.
	ListPublicChannels(ctx context.Context) ([]Channel, error)
	// Aggregates reactions for a batch of messages so the list endpoint can
	// hydrate the page in a single round-trip. The explicit cast on array_agg
	// lets sqlc infer []int64 instead of interface{}.
	ListReactionsForMessages(ctx context.Context, dollar_1 []int64) ([]ListReactionsForMessagesRow, error)
	// Every reply under a thread root, oldest first. Root is NOT included.
	ListThreadReplies(ctx context.Context, arg ListThreadRepliesParams) ([]Message, error)
	// Drives the River reminder job. Returns events starting in the
	// (now + lead_min, now + lead_max) window for users who RSVPd yes.
	// The job emits one `event.upcoming` realtime event per (event, user)
	// and stamps a reminder_sent sentinel elsewhere (not yet — future).
	ListUpcomingEventsForReminders(ctx context.Context, arg ListUpcomingEventsForRemindersParams) ([]ListUpcomingEventsForRemindersRow, error)
	// Every row for the current user in the current workspace. Drives unread
	// badges for the sidebar.
	ListUserChannelMemberships(ctx context.Context, arg ListUserChannelMembershipsParams) ([]ChannelMembership, error)
	// Every channel id the user belongs to inside a single workspace. Used to
	// validate that a user-supplied in:#channel operator resolves to a channel
	// they can see before we send it to Meilisearch as a filter.
	ListUserChannelMembershipsForWorkspace(ctx context.Context, arg ListUserChannelMembershipsForWorkspaceParams) ([]int64, error)
	ListWorkspaceMembers(ctx context.Context, workspaceID int64) ([]ListWorkspaceMembersRow, error)
	// Returns every workspace the current user is an active member of, with
	// their role and joined_at included. Sorted by the name of the workspace
	// for stable switcher ordering. M7 adds custom_status + notify_pref so
	// the switcher can render status badges + per-workspace mute indicators
	// without a second round trip.
	ListWorkspacesForUser(ctx context.Context, userID int64) ([]ListWorkspacesForUserRow, error)
	// Used to validate that a list of <@N> mention targets are actually in
	// the current workspace before persisting mention rows.
	LookupWorkspaceMembersByIDs(ctx context.Context, arg LookupWorkspaceMembersByIDsParams) ([]LookupWorkspaceMembersByIDsRow, error)
	MarkEmailVerified(ctx context.Context, id int64) error
	// Owner-pool path. Stamps the accept so the same token can't be reused.
	MarkInviteAccepted(ctx context.Context, arg MarkInviteAcceptedParams) error
	// Keeps the row pending (processed_at null) so another attempt will pick it
	// up after the claim's lock expires. last_error carries the message for
	// operators; attempts is already incremented by the claim itself.
	MarkSearchOutboxFailed(ctx context.Context, arg MarkSearchOutboxFailedParams) error
	// Idempotent — reapplying is safe because processed_at stays set.
	MarkSearchOutboxProcessed(ctx context.Context, ids []int64) error
	MessageHasAttachments(ctx context.Context, messageID int64) (bool, error)
	// Retention: keep at most $2 snapshots per page (newest first).
	PruneOldSnapshots(ctx context.Context, arg PruneOldSnapshotsParams) error
	// Housekeeping: drop processed rows older than the retention window. Run
	// periodically by the worker.
	PruneProcessedSearchOutbox(ctx context.Context, retain string) error
	RemoveAttendee(ctx context.Context, arg RemoveAttendeeParams) error
	RemoveReaction(ctx context.Context, arg RemoveReactionParams) error
	ResetFailedLogins(ctx context.Context, id int64) error
	RevokeAllUserSessions(ctx context.Context, userID int64) error
	// Admin path. RLS gate on workspace + role applies.
	RevokeInvite(ctx context.Context, arg RevokeInviteParams) error
	RevokeSession(ctx context.Context, id int64) error
	RotateSessionRefresh(ctx context.Context, arg RotateSessionRefreshParams) error
	// Stamp the external id + etag after a successful push or on import.
	SetEventExternalRef(ctx context.Context, arg SetEventExternalRefParams) error
	// Stamp the canonical LiveKit room name after we know the meeting id.
	// Room names are derived from the id, so we assign sequentially.
	SetMeetingLiveKitRoom(ctx context.Context, arg SetMeetingLiveKitRoomParams) error
	SoftDeleteFile(ctx context.Context, id int64) error
	SoftDeleteMessage(ctx context.Context, arg SoftDeleteMessageParams) (Message, error)
	TouchPage(ctx context.Context, id int64) error
	TouchSession(ctx context.Context, id int64) error
	UnarchivePage(ctx context.Context, id int64) error
	// Internal users update their own row. The handler enforces ownership;
	// the query itself is keyed on (event, user) so crafting a request for
	// someone else's row requires writing past the handler's checks.
	UpdateAttendeeRSVP(ctx context.Context, arg UpdateAttendeeRSVPParams) (EventAttendee, error)
	// Patch-style update: every field is COALESCE'd so the caller can null-out
	// channel_id / rrule / description / location_url etc. by passing an
	// explicit value.
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	UpdateExternalCalendarSyncState(ctx context.Context, arg UpdateExternalCalendarSyncStateParams) error
	// Used by the WOPI PutFile handler when Collabora saves a new version of
	// a document. sha256 + size_bytes change; the storage_key stays constant
	// so any existing attachments keep pointing at the same file id.
	// scan_status resets to 'pending' so the AV worker (M5.1) re-scans once
	// it's wired.
	UpdateFileBytes(ctx context.Context, arg UpdateFileBytesParams) error
	UpdateFileDerivatives(ctx context.Context, arg UpdateFileDerivativesParams) error
	UpdateFileScanStatus(ctx context.Context, arg UpdateFileScanStatusParams) error
	UpdateLastRead(ctx context.Context, arg UpdateLastReadParams) error
	// Caller sets custom_status to arbitrary JSONB. Pass '{}'::jsonb to clear.
	// RLS on workspace_memberships allows this because the modify policy
	// lets a user update their own rows (user_id match), so app.workspace_id
	// does not need to be set on this path.
	UpdateMembershipCustomStatus(ctx context.Context, arg UpdateMembershipCustomStatusParams) (WorkspaceMembership, error)
	// Workspace-level notification default. Same RLS story as custom_status:
	// the user is updating their own row, which the wsm_modify policy permits.
	UpdateMembershipNotifyPref(ctx context.Context, arg UpdateMembershipNotifyPrefParams) (WorkspaceMembership, error)
	UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) error
	UpdateMessageBody(ctx context.Context, arg UpdateMessageBodyParams) (Message, error)
	// Patch-style update. channel_id is always written: pass the current
	// value (from GetPageByID) to leave it unchanged, or NULL to detach.
	UpdatePage(ctx context.Context, arg UpdatePageParams) (Page, error)
	UpdatePageComment(ctx context.Context, arg UpdatePageCommentParams) (PageComment, error)
	UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error)
	// Email-only attendees (external guests). Same pattern.
	UpsertExternalAttendee(ctx context.Context, arg UpsertExternalAttendeeParams) (EventAttendee, error)
	// External-calendar connections + sync state (M9-P3).
	// Connect or reconnect. When reconnecting after a prior disconnect we
	// reset sync_token so the next pull starts from scratch (otherwise a
	// stale token tied to a deleted Google connection will 400).
	UpsertExternalCalendar(ctx context.Context, arg UpsertExternalCalendarParams) (ExternalCalendar, error)
	// ---- event_attendees ---------------------------------------------------
	// Idempotent attendee add for an internal user. If they're already on
	// the invite list, we keep their existing RSVP. If this is an import
	// from an external calendar, the caller passes rsvp='pending' and the
	// next sync tick will reconcile.
	UpsertInternalAttendee(ctx context.Context, arg UpsertInternalAttendeeParams) (EventAttendee, error)
}

var _ Querier = (*Queries)(nil)
