// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimSearchOutboxBatch = `-- name: ClaimSearchOutboxBatch :many
WITH claimed AS (
    SELECT id
    FROM search_outbox
    WHERE processed_at IS NULL
      AND attempts < $1::int
    ORDER BY enqueued_at
    LIMIT $2::int
    FOR UPDATE SKIP LOCKED
)
UPDATE search_outbox o
SET attempts = o.attempts + 1
FROM claimed
WHERE o.id = claimed.id
RETURNING o.id, o.workspace_id, o.kind, o.action, o.target_id, o.payload,
          o.enqueued_at, o.attempts
`

type ClaimSearchOutboxBatchParams struct {
	MaxAttempts int32
	BatchLimit  int32
}

type ClaimSearchOutboxBatchRow struct {
	ID          int64
	WorkspaceID int64
	Kind        string
	Action      string
	TargetID    int64
	Payload     []byte
	EnqueuedAt  pgtype.Timestamptz
	Attempts    int32
}

// Locks up to `limit` pending rows for this worker to process. FOR UPDATE
// SKIP LOCKED lets multiple workers share the queue without serializing
// on a single row. Rows with too many failures are skipped so one poison
// message can't block the backlog; poison rows stay visible via the
// idx_search_outbox_errors index for manual inspection.
func (q *Queries) ClaimSearchOutboxBatch(ctx context.Context, arg ClaimSearchOutboxBatchParams) ([]ClaimSearchOutboxBatchRow, error) {
	rows, err := q.db.Query(ctx, claimSearchOutboxBatch, arg.MaxAttempts, arg.BatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimSearchOutboxBatchRow{}
	for rows.Next() {
		var i ClaimSearchOutboxBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Kind,
			&i.Action,
			&i.TargetID,
			&i.Payload,
			&i.EnqueuedAt,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPendingSearchOutbox = `-- name: CountPendingSearchOutbox :one
SELECT count(*)::bigint AS n FROM search_outbox WHERE processed_at IS NULL
`

func (q *Queries) CountPendingSearchOutbox(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingSearchOutbox)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const enqueueSearchOutbox = `-- name: EnqueueSearchOutbox :exec

INSERT INTO search_outbox (workspace_id, kind, action, target_id, payload)
VALUES ($1, $2, $3, $4, $5)
`

type EnqueueSearchOutboxParams struct {
	WorkspaceID int64
	Kind        string
	Action      string
	TargetID    int64
	Payload     []byte
}

// Search outbox + hydration queries (M6).
//
// Writes to the outbox happen inside message-mutation transactions (with
// app.workspace_id set, so the tenant RLS policy applies). Reads / updates
// from the drain worker use a privileged owner-pool that bypasses RLS —
// see internal/db.OpenOwner.
// Enqueues one search-index event. Must run inside the same tx as the
// originating write so indexing state can never diverge from DB state.
func (q *Queries) EnqueueSearchOutbox(ctx context.Context, arg EnqueueSearchOutboxParams) error {
	_, err := q.db.Exec(ctx, enqueueSearchOutbox,
		arg.WorkspaceID,
		arg.Kind,
		arg.Action,
		arg.TargetID,
		arg.Payload,
	)
	return err
}

const getMessageForIndexing = `-- name: GetMessageForIndexing :one

SELECT m.id, m.workspace_id, m.channel_id, m.author_user_id, m.body_md,
       m.thread_root_id, m.parent_id, m.edited_at, m.deleted_at, m.created_at,
       c.type AS channel_type, c.name AS channel_name
FROM messages m
JOIN channels c ON c.id = m.channel_id
WHERE m.id = $1 AND m.created_at >= $2
`

type GetMessageForIndexingParams struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
}

type GetMessageForIndexingRow struct {
	ID           int64
	WorkspaceID  int64
	ChannelID    int64
	AuthorUserID *int64
	BodyMd       string
	ThreadRootID *int64
	ParentID     *int64
	EditedAt     pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	ChannelType  string
	ChannelName  *string
}

// ---- hydration queries ----------------------------------------------------
// Fetch the current state of a message plus the channel it lives in for
// building a Meilisearch document. Runs on the owner pool — RLS bypassed.
// The partition prune lower bound is expressed in months: the worker passes
// a timestamp computed from the outbox enqueued_at minus a small slack
// window so partition pruning still helps even if the indexer runs late.
func (q *Queries) GetMessageForIndexing(ctx context.Context, arg GetMessageForIndexingParams) (GetMessageForIndexingRow, error) {
	row := q.db.QueryRow(ctx, getMessageForIndexing, arg.ID, arg.CreatedAt)
	var i GetMessageForIndexingRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ChannelID,
		&i.AuthorUserID,
		&i.BodyMd,
		&i.ThreadRootID,
		&i.ParentID,
		&i.EditedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.ChannelType,
		&i.ChannelName,
	)
	return i, err
}

const getMessagesByIDsForSearch = `-- name: GetMessagesByIDsForSearch :many

SELECT m.id, m.workspace_id, m.channel_id, m.author_user_id, m.body_md,
       m.thread_root_id, m.parent_id, m.edited_at, m.created_at,
       c.name AS channel_name, c.type AS channel_type,
       u.display_name AS author_display_name
FROM messages m
JOIN channels c ON c.id = m.channel_id
LEFT JOIN users u ON u.id = m.author_user_id
WHERE m.id = ANY($1::bigint[])
  AND m.created_at >= $2::timestamptz
  AND m.deleted_at IS NULL
`

type GetMessagesByIDsForSearchParams struct {
	Ids        []int64
	LowerBound pgtype.Timestamptz
}

type GetMessagesByIDsForSearchRow struct {
	ID                int64
	WorkspaceID       int64
	ChannelID         int64
	AuthorUserID      *int64
	BodyMd            string
	ThreadRootID      *int64
	ParentID          *int64
	EditedAt          pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	ChannelName       *string
	ChannelType       string
	AuthorDisplayName *string
}

// ---- search-result hydration (runs under user's workspace GUC) ------------
// Called by POST /search after Meilisearch returns a ranked list of message
// ids. Uses the user's workspace + user GUCs so RLS double-checks visibility
// — any stale doc whose membership was revoked between index-time and query-
// time is silently dropped. Soft-deleted messages are also filtered out.
func (q *Queries) GetMessagesByIDsForSearch(ctx context.Context, arg GetMessagesByIDsForSearchParams) ([]GetMessagesByIDsForSearchRow, error) {
	rows, err := q.db.Query(ctx, getMessagesByIDsForSearch, arg.Ids, arg.LowerBound)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMessagesByIDsForSearchRow{}
	for rows.Next() {
		var i GetMessagesByIDsForSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ChannelID,
			&i.AuthorUserID,
			&i.BodyMd,
			&i.ThreadRootID,
			&i.ParentID,
			&i.EditedAt,
			&i.CreatedAt,
			&i.ChannelName,
			&i.ChannelType,
			&i.AuthorDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelMemberIDs = `-- name: ListChannelMemberIDs :many
SELECT user_id FROM channel_memberships
WHERE channel_id = $1
`

// Returns every user id with an active channel membership. Used to bake
// `channel_member_ids` into Meilisearch documents for private channels / DMs.
func (q *Queries) ListChannelMemberIDs(ctx context.Context, channelID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listChannelMemberIDs, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessageIDsForBackfill = `-- name: ListMessageIDsForBackfill :many

SELECT id, workspace_id, created_at
FROM messages
WHERE deleted_at IS NULL
  AND (created_at, id) > ($1::timestamptz, $2::bigint)
  AND created_at >= $3::timestamptz
ORDER BY created_at, id
LIMIT $4::int
`

type ListMessageIDsForBackfillParams struct {
	CursorCreatedAt pgtype.Timestamptz
	CursorID        int64
	LowerBound      pgtype.Timestamptz
	BatchLimit      int32
}

type ListMessageIDsForBackfillRow struct {
	ID          int64
	WorkspaceID int64
	CreatedAt   pgtype.Timestamptz
}

// ---- bootstrap / full reindex --------------------------------------------
// Streaming-style pagination for the initial / full reindex path. Returns
// message ids newer than the cursor, capped at `limit`, so the caller can
// iterate until empty. Excluded: soft-deleted messages (they'd be deleted
// from the index anyway).
func (q *Queries) ListMessageIDsForBackfill(ctx context.Context, arg ListMessageIDsForBackfillParams) ([]ListMessageIDsForBackfillRow, error) {
	rows, err := q.db.Query(ctx, listMessageIDsForBackfill,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LowerBound,
		arg.BatchLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessageIDsForBackfillRow{}
	for rows.Next() {
		var i ListMessageIDsForBackfillRow
		if err := rows.Scan(&i.ID, &i.WorkspaceID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserChannelMembershipsForWorkspace = `-- name: ListUserChannelMembershipsForWorkspace :many
SELECT channel_id FROM channel_memberships
WHERE user_id = $1 AND workspace_id = $2
`

type ListUserChannelMembershipsForWorkspaceParams struct {
	UserID      int64
	WorkspaceID int64
}

// Every channel id the user belongs to inside a single workspace. Used to
// validate that a user-supplied in:#channel operator resolves to a channel
// they can see before we send it to Meilisearch as a filter.
func (q *Queries) ListUserChannelMembershipsForWorkspace(ctx context.Context, arg ListUserChannelMembershipsForWorkspaceParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listUserChannelMembershipsForWorkspace, arg.UserID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var channel_id int64
		if err := rows.Scan(&channel_id); err != nil {
			return nil, err
		}
		items = append(items, channel_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSearchOutboxFailed = `-- name: MarkSearchOutboxFailed :exec
UPDATE search_outbox
SET last_error = $2
WHERE id = $1
`

type MarkSearchOutboxFailedParams struct {
	ID        int64
	LastError *string
}

// Keeps the row pending (processed_at null) so another attempt will pick it
// up after the claim's lock expires. last_error carries the message for
// operators; attempts is already incremented by the claim itself.
func (q *Queries) MarkSearchOutboxFailed(ctx context.Context, arg MarkSearchOutboxFailedParams) error {
	_, err := q.db.Exec(ctx, markSearchOutboxFailed, arg.ID, arg.LastError)
	return err
}

const markSearchOutboxProcessed = `-- name: MarkSearchOutboxProcessed :exec
UPDATE search_outbox
SET processed_at = now(), last_error = NULL
WHERE id = ANY($1::bigint[])
`

// Idempotent — reapplying is safe because processed_at stays set.
func (q *Queries) MarkSearchOutboxProcessed(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, markSearchOutboxProcessed, ids)
	return err
}

const messageHasAttachments = `-- name: MessageHasAttachments :one
SELECT EXISTS (
    SELECT 1 FROM message_attachments WHERE message_id = $1
)::bool AS has_files
`

func (q *Queries) MessageHasAttachments(ctx context.Context, messageID int64) (bool, error) {
	row := q.db.QueryRow(ctx, messageHasAttachments, messageID)
	var has_files bool
	err := row.Scan(&has_files)
	return has_files, err
}

const pruneProcessedSearchOutbox = `-- name: PruneProcessedSearchOutbox :exec
DELETE FROM search_outbox
WHERE processed_at IS NOT NULL
  AND processed_at < now() - ($1::text)::interval
`

// Housekeeping: drop processed rows older than the retention window. Run
// periodically by the worker.
func (q *Queries) PruneProcessedSearchOutbox(ctx context.Context, retain string) error {
	_, err := q.db.Exec(ctx, pruneProcessedSearchOutbox, retain)
	return err
}
