// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlcgen

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, refresh_token_hash, user_agent, ip, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, workspace_id, refresh_token_hash, user_agent, ip, created_at, last_seen_at, expires_at, revoked_at
`

type CreateSessionParams struct {
	UserID           int64
	RefreshTokenHash []byte
	UserAgent        string
	Ip               *netip.Addr
	ExpiresAt        pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.UserAgent,
		arg.Ip,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkspaceID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.Ip,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSessionByRefreshHash = `-- name: GetSessionByRefreshHash :one
SELECT id, user_id, workspace_id, refresh_token_hash, user_agent, ip, created_at, last_seen_at, expires_at, revoked_at FROM sessions
WHERE refresh_token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetSessionByRefreshHash(ctx context.Context, refreshTokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkspaceID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.Ip,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE sessions
SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const rotateSessionRefresh = `-- name: RotateSessionRefresh :exec
UPDATE sessions
SET refresh_token_hash = $2,
    last_seen_at       = now(),
    expires_at         = $3
WHERE id = $1
`

type RotateSessionRefreshParams struct {
	ID               int64
	RefreshTokenHash []byte
	ExpiresAt        pgtype.Timestamptz
}

func (q *Queries) RotateSessionRefresh(ctx context.Context, arg RotateSessionRefreshParams) error {
	_, err := q.db.Exec(ctx, rotateSessionRefresh, arg.ID, arg.RefreshTokenHash, arg.ExpiresAt)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_seen_at = now()
WHERE id = $1
`

func (q *Queries) TouchSession(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}
