// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, display_name)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, display_name, avatar_file_id, email_verified_at, totp_secret, locked_until, failed_login_count, created_at, updated_at, deactivated_at, dnd_enabled_until, quiet_hours_start, quiet_hours_end, quiet_hours_tz, is_bot, bot_app_installation_id
`

type CreateUserParams struct {
	Email        string
	PasswordHash *string
	DisplayName  string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarFileID,
		&i.EmailVerifiedAt,
		&i.TotpSecret,
		&i.LockedUntil,
		&i.FailedLoginCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
		&i.DndEnabledUntil,
		&i.QuietHoursStart,
		&i.QuietHoursEnd,
		&i.QuietHoursTz,
		&i.IsBot,
		&i.BotAppInstallationID,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, display_name, avatar_file_id, email_verified_at, totp_secret, locked_until, failed_login_count, created_at, updated_at, deactivated_at, dnd_enabled_until, quiet_hours_start, quiet_hours_end, quiet_hours_tz, is_bot, bot_app_installation_id FROM users
WHERE email = $1 AND deactivated_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarFileID,
		&i.EmailVerifiedAt,
		&i.TotpSecret,
		&i.LockedUntil,
		&i.FailedLoginCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
		&i.DndEnabledUntil,
		&i.QuietHoursStart,
		&i.QuietHoursEnd,
		&i.QuietHoursTz,
		&i.IsBot,
		&i.BotAppInstallationID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, display_name, avatar_file_id, email_verified_at, totp_secret, locked_until, failed_login_count, created_at, updated_at, deactivated_at, dnd_enabled_until, quiet_hours_start, quiet_hours_end, quiet_hours_tz, is_bot, bot_app_installation_id FROM users
WHERE id = $1 AND deactivated_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarFileID,
		&i.EmailVerifiedAt,
		&i.TotpSecret,
		&i.LockedUntil,
		&i.FailedLoginCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
		&i.DndEnabledUntil,
		&i.QuietHoursStart,
		&i.QuietHoursEnd,
		&i.QuietHoursTz,
		&i.IsBot,
		&i.BotAppInstallationID,
	)
	return i, err
}

const incrementFailedLogins = `-- name: IncrementFailedLogins :one
UPDATE users
SET failed_login_count = failed_login_count + 1,
    locked_until = CASE
                      WHEN failed_login_count + 1 >= $2 THEN now() + ($3 || ' minutes')::interval
                      ELSE locked_until
                   END
WHERE id = $1
RETURNING failed_login_count, locked_until
`

type IncrementFailedLoginsParams struct {
	ID               int64
	FailedLoginCount int32
	Column3          *string
}

type IncrementFailedLoginsRow struct {
	FailedLoginCount int32
	LockedUntil      pgtype.Timestamptz
}

func (q *Queries) IncrementFailedLogins(ctx context.Context, arg IncrementFailedLoginsParams) (IncrementFailedLoginsRow, error) {
	row := q.db.QueryRow(ctx, incrementFailedLogins, arg.ID, arg.FailedLoginCount, arg.Column3)
	var i IncrementFailedLoginsRow
	err := row.Scan(&i.FailedLoginCount, &i.LockedUntil)
	return i, err
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE users
SET email_verified_at = COALESCE(email_verified_at, now())
WHERE id = $1
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markEmailVerified, id)
	return err
}

const resetFailedLogins = `-- name: ResetFailedLogins :exec
UPDATE users
SET failed_login_count = 0,
    locked_until       = NULL
WHERE id = $1
`

func (q *Queries) ResetFailedLogins(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, resetFailedLogins, id)
	return err
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :exec
UPDATE users
SET display_name = $2
WHERE id = $1
`

type UpdateUserDisplayNameParams struct {
	ID          int64
	DisplayName string
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) error {
	_, err := q.db.Exec(ctx, updateUserDisplayName, arg.ID, arg.DisplayName)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash      = $2,
    failed_login_count = 0,
    locked_until       = NULL
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           int64
	PasswordHash *string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
