// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package sqlcgen

import (
	"context"
)

const createBotMessage = `-- name: CreateBotMessage :one

INSERT INTO messages
    (workspace_id, channel_id, author_user_id, author_bot_installation_id,
     body_md, body_blocks, thread_root_id, parent_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, workspace_id, channel_id, thread_root_id, parent_id, author_user_id, author_bot_id, body_md, body_blocks, edited_at, deleted_at, created_at, author_bot_installation_id
`

type CreateBotMessageParams struct {
	WorkspaceID             int64
	ChannelID               int64
	AuthorUserID            *int64
	AuthorBotInstallationID *int64
	BodyMd                  string
	BodyBlocks              []byte
	ThreadRootID            *int64
	ParentID                *int64
}

// ---- messages for bot API ----------------------------------------------
func (q *Queries) CreateBotMessage(ctx context.Context, arg CreateBotMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createBotMessage,
		arg.WorkspaceID,
		arg.ChannelID,
		arg.AuthorUserID,
		arg.AuthorBotInstallationID,
		arg.BodyMd,
		arg.BodyBlocks,
		arg.ThreadRootID,
		arg.ParentID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ChannelID,
		&i.ThreadRootID,
		&i.ParentID,
		&i.AuthorUserID,
		&i.AuthorBotID,
		&i.BodyMd,
		&i.BodyBlocks,
		&i.EditedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.AuthorBotInstallationID,
	)
	return i, err
}

const createIncomingWebhook = `-- name: CreateIncomingWebhook :one


INSERT INTO webhooks_incoming (workspace_id, channel_id, name, token, signing_secret_hash, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, channel_id, name, token, signing_secret_hash, created_by, created_at, last_used_at, deleted_at
`

type CreateIncomingWebhookParams struct {
	WorkspaceID       int64
	ChannelID         int64
	Name              string
	Token             string
	SigningSecretHash string
	CreatedBy         *int64
}

// Webhooks + slash commands (M12-P2).
// ---- webhooks_incoming --------------------------------------------------
func (q *Queries) CreateIncomingWebhook(ctx context.Context, arg CreateIncomingWebhookParams) (WebhooksIncoming, error) {
	row := q.db.QueryRow(ctx, createIncomingWebhook,
		arg.WorkspaceID,
		arg.ChannelID,
		arg.Name,
		arg.Token,
		arg.SigningSecretHash,
		arg.CreatedBy,
	)
	var i WebhooksIncoming
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ChannelID,
		&i.Name,
		&i.Token,
		&i.SigningSecretHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createOutgoingWebhook = `-- name: CreateOutgoingWebhook :one

INSERT INTO webhooks_outgoing
    (workspace_id, app_installation_id, event_pattern, target_url, signing_secret_hash)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, app_installation_id, event_pattern, target_url, signing_secret_hash, created_at, deleted_at
`

type CreateOutgoingWebhookParams struct {
	WorkspaceID       int64
	AppInstallationID int64
	EventPattern      string
	TargetUrl         string
	SigningSecretHash string
}

// ---- webhooks_outgoing --------------------------------------------------
func (q *Queries) CreateOutgoingWebhook(ctx context.Context, arg CreateOutgoingWebhookParams) (WebhooksOutgoing, error) {
	row := q.db.QueryRow(ctx, createOutgoingWebhook,
		arg.WorkspaceID,
		arg.AppInstallationID,
		arg.EventPattern,
		arg.TargetUrl,
		arg.SigningSecretHash,
	)
	var i WebhooksOutgoing
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AppInstallationID,
		&i.EventPattern,
		&i.TargetUrl,
		&i.SigningSecretHash,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteIncomingWebhook = `-- name: DeleteIncomingWebhook :exec
UPDATE webhooks_incoming SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteIncomingWebhook(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteIncomingWebhook, id)
	return err
}

const deleteOutgoingWebhook = `-- name: DeleteOutgoingWebhook :exec
UPDATE webhooks_outgoing SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteOutgoingWebhook(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteOutgoingWebhook, id)
	return err
}

const deleteSlashCommand = `-- name: DeleteSlashCommand :exec
UPDATE slash_commands SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteSlashCommand(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSlashCommand, id)
	return err
}

const getIncomingWebhookByToken = `-- name: GetIncomingWebhookByToken :one
SELECT id, workspace_id, channel_id, name, token, signing_secret_hash, created_by, created_at, last_used_at, deleted_at FROM webhooks_incoming
WHERE token = $1 AND deleted_at IS NULL
`

// NOTE: called unauthenticated from a public URL. Uses the owner pool in
// the handler so RLS doesn't hide the row.
func (q *Queries) GetIncomingWebhookByToken(ctx context.Context, token string) (WebhooksIncoming, error) {
	row := q.db.QueryRow(ctx, getIncomingWebhookByToken, token)
	var i WebhooksIncoming
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ChannelID,
		&i.Name,
		&i.Token,
		&i.SigningSecretHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSlashCommandForWorkspace = `-- name: GetSlashCommandForWorkspace :one
SELECT id, workspace_id, app_installation_id, command, target_url, description, usage_hint, signing_secret_hash, created_at, deleted_at FROM slash_commands
WHERE workspace_id = $1 AND command = $2 AND deleted_at IS NULL
`

type GetSlashCommandForWorkspaceParams struct {
	WorkspaceID int64
	Command     string
}

func (q *Queries) GetSlashCommandForWorkspace(ctx context.Context, arg GetSlashCommandForWorkspaceParams) (SlashCommand, error) {
	row := q.db.QueryRow(ctx, getSlashCommandForWorkspace, arg.WorkspaceID, arg.Command)
	var i SlashCommand
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AppInstallationID,
		&i.Command,
		&i.TargetUrl,
		&i.Description,
		&i.UsageHint,
		&i.SigningSecretHash,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listIncomingWebhooks = `-- name: ListIncomingWebhooks :many
SELECT id, workspace_id, channel_id, name, token, signing_secret_hash, created_by, created_at, last_used_at, deleted_at FROM webhooks_incoming
WHERE workspace_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListIncomingWebhooks(ctx context.Context, workspaceID int64) ([]WebhooksIncoming, error) {
	rows, err := q.db.Query(ctx, listIncomingWebhooks, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhooksIncoming{}
	for rows.Next() {
		var i WebhooksIncoming
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ChannelID,
			&i.Name,
			&i.Token,
			&i.SigningSecretHash,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutgoingWebhooksForEvent = `-- name: ListOutgoingWebhooksForEvent :many
SELECT id, workspace_id, app_installation_id, event_pattern, target_url, signing_secret_hash, created_at, deleted_at FROM webhooks_outgoing
WHERE workspace_id = $1
  AND (event_pattern = $2 OR event_pattern = '*')
  AND deleted_at IS NULL
`

type ListOutgoingWebhooksForEventParams struct {
	WorkspaceID  int64
	EventPattern string
}

// Matches any registered subscription where the pattern is exactly the
// event OR a catch-all "*". Used by the fanout worker.
func (q *Queries) ListOutgoingWebhooksForEvent(ctx context.Context, arg ListOutgoingWebhooksForEventParams) ([]WebhooksOutgoing, error) {
	rows, err := q.db.Query(ctx, listOutgoingWebhooksForEvent, arg.WorkspaceID, arg.EventPattern)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhooksOutgoing{}
	for rows.Next() {
		var i WebhooksOutgoing
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AppInstallationID,
			&i.EventPattern,
			&i.TargetUrl,
			&i.SigningSecretHash,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutgoingWebhooksForInstallation = `-- name: ListOutgoingWebhooksForInstallation :many
SELECT id, workspace_id, app_installation_id, event_pattern, target_url, signing_secret_hash, created_at, deleted_at FROM webhooks_outgoing
WHERE app_installation_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListOutgoingWebhooksForInstallation(ctx context.Context, appInstallationID int64) ([]WebhooksOutgoing, error) {
	rows, err := q.db.Query(ctx, listOutgoingWebhooksForInstallation, appInstallationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhooksOutgoing{}
	for rows.Next() {
		var i WebhooksOutgoing
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AppInstallationID,
			&i.EventPattern,
			&i.TargetUrl,
			&i.SigningSecretHash,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlashCommandsForWorkspace = `-- name: ListSlashCommandsForWorkspace :many
SELECT id, workspace_id, app_installation_id, command, target_url, description, usage_hint, signing_secret_hash, created_at, deleted_at FROM slash_commands
WHERE workspace_id = $1 AND deleted_at IS NULL
ORDER BY command
`

func (q *Queries) ListSlashCommandsForWorkspace(ctx context.Context, workspaceID int64) ([]SlashCommand, error) {
	rows, err := q.db.Query(ctx, listSlashCommandsForWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SlashCommand{}
	for rows.Next() {
		var i SlashCommand
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AppInstallationID,
			&i.Command,
			&i.TargetUrl,
			&i.Description,
			&i.UsageHint,
			&i.SigningSecretHash,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerSlashCommand = `-- name: RegisterSlashCommand :one

INSERT INTO slash_commands (workspace_id, app_installation_id, command,
                            target_url, description, usage_hint, signing_secret_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workspace_id, app_installation_id, command, target_url, description, usage_hint, signing_secret_hash, created_at, deleted_at
`

type RegisterSlashCommandParams struct {
	WorkspaceID       int64
	AppInstallationID int64
	Command           string
	TargetUrl         string
	Description       string
	UsageHint         string
	SigningSecretHash string
}

// ---- slash_commands -----------------------------------------------------
func (q *Queries) RegisterSlashCommand(ctx context.Context, arg RegisterSlashCommandParams) (SlashCommand, error) {
	row := q.db.QueryRow(ctx, registerSlashCommand,
		arg.WorkspaceID,
		arg.AppInstallationID,
		arg.Command,
		arg.TargetUrl,
		arg.Description,
		arg.UsageHint,
		arg.SigningSecretHash,
	)
	var i SlashCommand
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AppInstallationID,
		&i.Command,
		&i.TargetUrl,
		&i.Description,
		&i.UsageHint,
		&i.SigningSecretHash,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const touchIncomingWebhook = `-- name: TouchIncomingWebhook :exec
UPDATE webhooks_incoming SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchIncomingWebhook(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchIncomingWebhook, id)
	return err
}
