// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveWorkspace = `-- name: ArchiveWorkspace :exec
UPDATE workspaces
SET archived_at = now()
WHERE id = $1
`

func (q *Queries) ArchiveWorkspace(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, archiveWorkspace, id)
	return err
}

const countWorkspacesForUser = `-- name: CountWorkspacesForUser :one
SELECT count(*) AS n
FROM workspace_memberships m
WHERE m.user_id = $1 AND m.deactivated_at IS NULL
`

func (q *Queries) CountWorkspacesForUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkspacesForUser, userID)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (slug, name, description, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, slug, name, description, brand_color, logo_file_id, retention_days, created_by, created_at, updated_at, archived_at
`

type CreateWorkspaceParams struct {
	Slug        string
	Name        string
	Description string
	CreatedBy   int64
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.CreatedBy,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.BrandColor,
		&i.LogoFileID,
		&i.RetentionDays,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, slug, name, description, brand_color, logo_file_id, retention_days, created_by, created_at, updated_at, archived_at FROM workspaces
WHERE id = $1 AND archived_at IS NULL
`

func (q *Queries) GetWorkspaceByID(ctx context.Context, id int64) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.BrandColor,
		&i.LogoFileID,
		&i.RetentionDays,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getWorkspaceBySlug = `-- name: GetWorkspaceBySlug :one
SELECT id, slug, name, description, brand_color, logo_file_id, retention_days, created_by, created_at, updated_at, archived_at FROM workspaces
WHERE slug = $1 AND archived_at IS NULL
`

func (q *Queries) GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceBySlug, slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.BrandColor,
		&i.LogoFileID,
		&i.RetentionDays,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listWorkspacesForUser = `-- name: ListWorkspacesForUser :many
SELECT w.id, w.slug, w.name, w.description, w.brand_color, w.logo_file_id, w.retention_days, w.created_by, w.created_at, w.updated_at, w.archived_at,
       m.role          AS membership_role,
       m.joined_at     AS membership_joined_at,
       m.custom_status AS membership_custom_status,
       m.notify_pref   AS membership_notify_pref
FROM workspaces w
JOIN workspace_memberships m ON m.workspace_id = w.id
WHERE m.user_id = $1
  AND m.deactivated_at IS NULL
  AND w.archived_at  IS NULL
ORDER BY w.name
`

type ListWorkspacesForUserRow struct {
	ID                     int64
	Slug                   string
	Name                   string
	Description            string
	BrandColor             *string
	LogoFileID             *int64
	RetentionDays          *int32
	CreatedBy              int64
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	ArchivedAt             pgtype.Timestamptz
	MembershipRole         string
	MembershipJoinedAt     pgtype.Timestamptz
	MembershipCustomStatus []byte
	MembershipNotifyPref   string
}

// Returns every workspace the current user is an active member of, with
// their role and joined_at included. Sorted by the name of the workspace
// for stable switcher ordering. M7 adds custom_status + notify_pref so
// the switcher can render status badges + per-workspace mute indicators
// without a second round trip.
func (q *Queries) ListWorkspacesForUser(ctx context.Context, userID int64) ([]ListWorkspacesForUserRow, error) {
	rows, err := q.db.Query(ctx, listWorkspacesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspacesForUserRow{}
	for rows.Next() {
		var i ListWorkspacesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.BrandColor,
			&i.LogoFileID,
			&i.RetentionDays,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.MembershipRole,
			&i.MembershipJoinedAt,
			&i.MembershipCustomStatus,
			&i.MembershipNotifyPref,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesWithRetention = `-- name: ListWorkspacesWithRetention :many
SELECT id, retention_days
FROM   workspaces
WHERE  retention_days IS NOT NULL AND retention_days > 0
  AND  archived_at IS NULL
`

type ListWorkspacesWithRetentionRow struct {
	ID            int64
	RetentionDays *int32
}

// Fed into the retention-sweep worker. Returns every workspace whose
// admins have opted into automatic message purging.
func (q *Queries) ListWorkspacesWithRetention(ctx context.Context) ([]ListWorkspacesWithRetentionRow, error) {
	rows, err := q.db.Query(ctx, listWorkspacesWithRetention)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspacesWithRetentionRow{}
	for rows.Next() {
		var i ListWorkspacesWithRetentionRow
		if err := rows.Scan(&i.ID, &i.RetentionDays); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeOldMessages = `-- name: PurgeOldMessages :exec
UPDATE messages
SET    deleted_at = now(),
       body_md    = '',
       body_blocks = '[]'::jsonb
WHERE  workspace_id = $1
  AND  created_at >= $2
  AND  created_at <  $3
  AND  deleted_at IS NULL
`

type PurgeOldMessagesParams struct {
	WorkspaceID int64
	CreatedAt   pgtype.Timestamptz
	CreatedAt_2 pgtype.Timestamptz
}

// Soft-delete messages older than the retention window. Messages are
// partitioned; the date bound is essential for partition pruning.
func (q *Queries) PurgeOldMessages(ctx context.Context, arg PurgeOldMessagesParams) error {
	_, err := q.db.Exec(ctx, purgeOldMessages, arg.WorkspaceID, arg.CreatedAt, arg.CreatedAt_2)
	return err
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspaces
SET name        = COALESCE($2, name),
    description = COALESCE($3, description),
    brand_color = COALESCE($4, brand_color)
WHERE id = $1
RETURNING id, slug, name, description, brand_color, logo_file_id, retention_days, created_by, created_at, updated_at, archived_at
`

type UpdateWorkspaceParams struct {
	ID          int64
	Name        string
	Description string
	BrandColor  *string
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspace,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.BrandColor,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.BrandColor,
		&i.LogoFileID,
		&i.RetentionDays,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateWorkspaceAdmin = `-- name: UpdateWorkspaceAdmin :one
UPDATE workspaces
SET name           = COALESCE($1::text,        name),
    description    = COALESCE($2::text, description),
    brand_color    = COALESCE($3::text, brand_color),
    logo_file_id   = COALESCE($4::bigint, logo_file_id),
    retention_days = $5::int
WHERE id = $6::bigint
RETURNING id, slug, name, description, brand_color, logo_file_id, retention_days, created_by, created_at, updated_at, archived_at
`

type UpdateWorkspaceAdminParams struct {
	Name          *string
	Description   *string
	BrandColor    *string
	LogoFileID    *int64
	RetentionDays *int32
	ID            int64
}

// Admin dashboard update — separately named so callers distinguish
// brand-change PATCHes from retention-policy changes (different audit
// events fire). retention_days is always written so the caller can
// null it out ("keep forever") explicitly.
func (q *Queries) UpdateWorkspaceAdmin(ctx context.Context, arg UpdateWorkspaceAdminParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceAdmin,
		arg.Name,
		arg.Description,
		arg.BrandColor,
		arg.LogoFileID,
		arg.RetentionDays,
		arg.ID,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.BrandColor,
		&i.LogoFileID,
		&i.RetentionDays,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
