// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace_email_settings.sql

package sqlcgen

import (
	"context"
)

const deleteWorkspaceEmailSettings = `-- name: DeleteWorkspaceEmailSettings :exec
DELETE FROM workspace_email_settings WHERE workspace_id = $1
`

func (q *Queries) DeleteWorkspaceEmailSettings(ctx context.Context, workspaceID int64) error {
	_, err := q.db.Exec(ctx, deleteWorkspaceEmailSettings, workspaceID)
	return err
}

const getWorkspaceEmailSettings = `-- name: GetWorkspaceEmailSettings :one

SELECT workspace_id, provider, resend_api_key_enc, from_address, from_name, updated_at, updated_by FROM workspace_email_settings
WHERE workspace_id = $1
`

// Per-workspace email provider config.
func (q *Queries) GetWorkspaceEmailSettings(ctx context.Context, workspaceID int64) (WorkspaceEmailSetting, error) {
	row := q.db.QueryRow(ctx, getWorkspaceEmailSettings, workspaceID)
	var i WorkspaceEmailSetting
	err := row.Scan(
		&i.WorkspaceID,
		&i.Provider,
		&i.ResendApiKeyEnc,
		&i.FromAddress,
		&i.FromName,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const upsertWorkspaceEmailSettings = `-- name: UpsertWorkspaceEmailSettings :one
INSERT INTO workspace_email_settings
    (workspace_id, provider, resend_api_key_enc, from_address, from_name, updated_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (workspace_id) DO UPDATE
SET provider           = EXCLUDED.provider,
    resend_api_key_enc = CASE
        -- Empty replacement means "keep existing key" — lets the UI omit
        -- the key when the admin only wants to change the from-address.
        WHEN EXCLUDED.resend_api_key_enc = '' THEN workspace_email_settings.resend_api_key_enc
        ELSE EXCLUDED.resend_api_key_enc
    END,
    from_address       = EXCLUDED.from_address,
    from_name          = EXCLUDED.from_name,
    updated_at         = now(),
    updated_by         = EXCLUDED.updated_by
RETURNING workspace_id, provider, resend_api_key_enc, from_address, from_name, updated_at, updated_by
`

type UpsertWorkspaceEmailSettingsParams struct {
	WorkspaceID     int64
	Provider        string
	ResendApiKeyEnc string
	FromAddress     string
	FromName        string
	UpdatedBy       *int64
}

func (q *Queries) UpsertWorkspaceEmailSettings(ctx context.Context, arg UpsertWorkspaceEmailSettingsParams) (WorkspaceEmailSetting, error) {
	row := q.db.QueryRow(ctx, upsertWorkspaceEmailSettings,
		arg.WorkspaceID,
		arg.Provider,
		arg.ResendApiKeyEnc,
		arg.FromAddress,
		arg.FromName,
		arg.UpdatedBy,
	)
	var i WorkspaceEmailSetting
	err := row.Scan(
		&i.WorkspaceID,
		&i.Provider,
		&i.ResendApiKeyEnc,
		&i.FromAddress,
		&i.FromName,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
