-- Workspace invite queries (M7).
--
-- Two call paths converge on this table:
--
--   Admin path (runtime pool, sliils_app role): create / list / revoke.
--     Relies on the invites_modify + invites_select RLS policies in
--     20260424000002_workspace_invites.sql — the admin must have the GUC
--     app.workspace_id set to the right workspace.
--
--   Accept path (owner pool, RLS bypassed): lookup by token, mark accepted,
--     create the workspace_membership. The token is the unguessable handle
--     so we don't need tenant scope to look it up; we verify the accepting
--     user's identity at the handler layer.

-- name: CreateWorkspaceInvite :one
-- Called by the admin flow. RLS enforces that app.workspace_id matches
-- the row's workspace_id AND the caller is an owner/admin of that
-- workspace. Token is generated by the handler and passed in.
INSERT INTO workspace_invites (workspace_id, token, email, role, created_by, expires_at)
VALUES ($1, $2, $3, COALESCE($4, 'member'), $5, $6)
RETURNING *;

-- name: ListPendingInvitesForWorkspace :many
-- Admin-facing list of outstanding invites. The partial index drives this.
SELECT i.id, i.workspace_id, i.token, i.email, i.role,
       i.created_by, i.created_at, i.expires_at,
       u.display_name AS creator_display_name, u.email AS creator_email
FROM workspace_invites i
LEFT JOIN users u ON u.id = i.created_by
WHERE i.workspace_id = $1
  AND i.accepted_at IS NULL
  AND i.revoked_at IS NULL
ORDER BY i.created_at DESC;

-- name: RevokeInvite :exec
-- Admin path. RLS gate on workspace + role applies.
UPDATE workspace_invites
SET revoked_at = now(), revoked_by = $2
WHERE id = $1
  AND accepted_at IS NULL
  AND revoked_at IS NULL;

-- name: GetInviteByToken :one
-- Token lookup. Runs on the OWNER pool (RLS bypassed) so the accept path
-- can find the invite without knowing the workspace id. The handler
-- validates expiry + revoked + accepted + email-match server-side before
-- acting on the result.
SELECT i.id, i.workspace_id, i.token, i.email, i.role,
       i.created_by, i.created_at, i.expires_at,
       i.accepted_at, i.accepted_by, i.revoked_at,
       w.slug AS workspace_slug, w.name AS workspace_name,
       w.description AS workspace_description
FROM workspace_invites i
JOIN workspaces w ON w.id = i.workspace_id
WHERE i.token = $1;

-- name: MarkInviteAccepted :exec
-- Owner-pool path. Stamps the accept so the same token can't be reused.
UPDATE workspace_invites
SET accepted_at = now(), accepted_by = $2
WHERE id = $1
  AND accepted_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > now();

-- name: InsertWorkspaceMembershipFromInvite :one
-- Owner-pool path for the accept. Bypasses the workspace_memberships
-- RLS policy (which requires app.workspace_id to be set — we don't
-- set it here because the accepting user hasn't "selected" the workspace
-- in their session yet). Safe because the token lookup above already
-- proved the caller's right to enroll.
--
-- ON CONFLICT reactivates only when the existing row is NOT marked
-- deactivated. A previously-deactivated membership is a deliberate
-- admin action (kicked user) that must not be undone by the ex-member
-- re-accepting an old invite URL. Returns no rows in that case; the
-- handler converts "no rows" to 403.
INSERT INTO workspace_memberships (workspace_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (workspace_id, user_id)
DO UPDATE SET
    role = EXCLUDED.role
    -- NB: deactivated_at is intentionally NOT cleared here. We only
    -- touch the role so a legitimate upgrade via reinvite still works,
    -- but a kicked user stays kicked until an admin reactivates them.
WHERE workspace_memberships.deactivated_at IS NULL
RETURNING *;

-- name: IsWorkspaceMembershipDeactivated :one
-- Probe used by the accept path so the handler can 403 with a clear
-- error instead of silently returning no rows from the conditional
-- upsert above.
SELECT count(*) > 0
FROM workspace_memberships
WHERE workspace_id = $1
  AND user_id      = $2
  AND deactivated_at IS NOT NULL;
